import { sampleFlawTrackers_1 } from './sampleFlawTrackers';

import {
  affectImpacts,
  affectAffectedness,
  affectResolutions,
  type ZodAffectType,
} from '@/types/zodAffect';

export function sampleFlawAffects_1(flawId: string): ZodAffectType[] {
  const affectUuid_1 = '3484da83-c08c-4bf8-87c0-640bfb8334f5';
  const affectUuid_2 = 'f300fbec-29ef-4b4d-8a01-bb210bd09d50';
  const affectUuid_3 = 'b0d28cd4-767c-423c-9195-819aca1c3c19';
  const affectUuid_4 = 'c0d31d9f-0e7d-4bc6-9134-5eba6acb483c';
  const affectUuid_5 = '525735df-4cb0-4ac4-83cb-2ec41c75e785';
  const affectUuid_6 = '70d82cd8-74a3-4020-9181-5d2a7a57e591';
  return [
    {
      uuid: affectUuid_1,
      flaw: flawId,
      affectedness: affectAffectedness.Affected,
      resolution: affectResolutions.Fix,
      ps_module: 'openshift-1',
      ps_component: 'openshift-1-1',
      impact: affectImpacts.Low,
      trackers: sampleFlawTrackers_1([affectUuid_1]),
      delegated_resolution: null,
      cvss_scores: [],
      embargoed: false,
      created_dt: '2021-09-13T09:09:38Z',
      updated_dt: '2023-12-06T17:12:21Z',
      alerts: [],
    },
    {
      uuid: affectUuid_2,
      flaw: flawId,
      affectedness: affectAffectedness.Affected,
      resolution: affectResolutions.Fix,
      ps_module: 'openshift-2',
      ps_component: 'openshift-2-1',
      impact: affectImpacts.Low,
      trackers: [],
      delegated_resolution: null,
      cvss_scores: [],
      embargoed: false,
      created_dt: '2021-09-13T09:09:38Z',
      updated_dt: '2023-12-06T17:12:21Z',
      alerts: [],
    },
    {
      uuid: affectUuid_3,
      flaw: flawId,
      affectedness: affectAffectedness.Affected,
      resolution: affectResolutions.Fix,
      ps_module: 'openshift-3',
      ps_component: 'openshift-3-1',
      impact: affectImpacts.Low,
      trackers: [],
      delegated_resolution: null,
      cvss_scores: [],
      embargoed: false,
      created_dt: '2021-09-13T09:09:38Z',
      updated_dt: '2023-12-06T17:12:21Z',
      alerts: [],
    },
    {
      uuid: affectUuid_4,
      flaw: flawId,
      affectedness: affectAffectedness.Affected,
      resolution: affectResolutions.Fix,
      ps_module: 'openshift-4',
      ps_component: 'openshift-4-1',
      impact: affectImpacts.Low,
      trackers: [],
      delegated_resolution: null,
      cvss_scores: [],
      embargoed: false,
      created_dt: '2021-09-13T09:09:38Z',
      updated_dt: '2023-12-06T17:12:21Z',
      alerts: [],
    },
    {
      uuid: affectUuid_5,
      flaw: flawId,
      affectedness: affectAffectedness.Affected,
      resolution: affectResolutions.Fix,
      ps_module: 'openshift-5-1',
      ps_component: 'openshift',
      impact: affectImpacts.Low,
      trackers: sampleFlawTrackers_1([affectUuid_5]),
      delegated_resolution: null,
      cvss_scores: [],
      embargoed: false,
      created_dt: '2021-09-13T09:09:38Z',
      updated_dt: '2023-12-06T17:12:21Z',
      alerts: [],
    },
    {
      uuid: affectUuid_6,
      flaw: flawId,
      affectedness: affectAffectedness.Empty,
      resolution: affectResolutions.Wontfix,
      ps_module: 'openshift-6-1',
      ps_component: 'openshift',
      impact: affectImpacts.Critical,
      trackers: [],
      delegated_resolution: null,
      cvss_scores: [],
      embargoed: false,
      created_dt: '2021-09-13T09:09:38Z',
      updated_dt: '2023-12-06T17:12:21Z',
      alerts: [],
    },
  ];
}
