<script setup lang="ts">
import AegisMitigationActions from '@/components/Aegis/AegisMitigationActions.vue';

import type { AegisSuggestionContextRefs } from '@/composables/aegis/useAegisSuggestionContext';
import { useAegisMetadataTracking } from '@/composables/aegis/useAegisMetadataTracking';

import LabelTextarea from '@/widgets/LabelTextarea/LabelTextarea.vue';
import { osimRuntime } from '@/stores/osimRuntime';

defineProps<{
  aegisContext: AegisSuggestionContextRefs;
  error?: null | string;
}>();

const modelValue = defineModel<null | string | undefined>();

const { isFieldValueAIBot } = useAegisMetadataTracking();
</script>

<template>
  <LabelTextarea
    v-model="modelValue"
    label="Mitigation"
    placeholder="Mitigation Text ..."
    :error="error"
  >
    <template v-if="osimRuntime.flags?.aiMitigationSuggestions" #label>
      <span
        class="form-label col-3 position-relative"
        :class="{
          'border-start border-primary border-3 bg-primary bg-opacity-10 ps-2':
            isFieldValueAIBot('mitigation', modelValue)
        }"
      >
        <i
          v-if="isFieldValueAIBot('mitigation', modelValue)"
          class="bi bi-robot text-primary me-1"
          title="Generated by OSIDB-Bot"
        >
        </i>
        <AegisMitigationActions v-model="modelValue" :aegisContext="aegisContext" />
        <span class="ms-2">Mitigation</span>
      </span>
    </template>
  </LabelTextarea>
</template>
