import type { SRPFieldSpec } from '@/types/cra';

// SRP field definitions for CRA milestone reporting.
// Keys match the backend additional_details field names defined in
// osidb/apps/regulatory_reporting/services.py (OVERRIDABLE_*_KEYS).
// Automated fields (notification_type, notification_level, product_identity)
// are derived server-side and not shown to coordinators.
// Columns: 24h, 72h, final — requirement per milestone stage.
export const SRP_FIELDS: SRPFieldSpec[] = [
  // ── Common fields ──────────────────────────────────────────────────────────
  { 'key': 'manufacturer_or_steward_name',
    'label': 'Manufacturer Name',
    'type': 'text',
    '24h': 'required',
    '72h': 'optional',
    'final': 'optional',
    'scope': 'common' },
  { 'key': 'member_states_available',
    'label': 'Member States Where Product Is Available',
    'type': 'text',
    'isList': true,
    '24h': 'required_if_available',
    '72h': 'optional',
    'final': 'optional',
    'scope': 'common' },
  { 'key': 'product_type',
    'label': 'Product Type (Default/Important/Critical)',
    'type': 'text',
    '24h': 'optional',
    '72h': 'optional',
    'final': 'optional',
    'scope': 'common' },
  { 'key': 'product_class',
    'label': 'Product Class',
    'type': 'text',
    '24h': 'optional',
    '72h': 'optional',
    'final': 'optional',
    'scope': 'common' },
  { 'key': 'product_category',
    'label': 'Product Category',
    'type': 'text',
    '24h': 'optional',
    '72h': 'optional',
    'final': 'optional',
    'scope': 'common' },
  { 'key': 'end_of_support',
    'label': 'End of Support Indicator',
    'type': 'text',
    '24h': 'optional',
    '72h': 'optional',
    'final': 'optional',
    'scope': 'common' },
  { 'key': 'mitigating_measure_expected_shortly',
    'label': 'Mitigating Measure Expected Shortly',
    'type': 'text',
    '24h': 'optional',
    '72h': 'optional',
    'final': 'optional',
    'scope': 'common' },
  { 'key': 'information_sensitivity',
    'label': 'Considered Sensitivity of Information',
    'type': 'text',
    '24h': 'optional',
    '72h': 'required_if_available',
    'final': 'optional',
    'scope': 'common' },
  { 'key': 'corrective_or_mitigating_measures_taken',
    'label': 'Corrective or Mitigating Measures Taken',
    'type': 'textarea',
    '24h': 'optional',
    '72h': 'required',
    'final': 'required',
    'scope': 'common' },
  { 'key': 'corrective_or_mitigating_measures_users_can_take',
    'label': 'Corrective or Mitigating Measures That Users Can Take',
    'type': 'textarea',
    '24h': 'optional',
    '72h': 'required',
    'final': 'required',
    'scope': 'common' },
  { 'key': 'attack_vector',
    'label': 'Attack Vector',
    'type': 'text',
    '24h': 'optional',
    '72h': 'optional',
    'final': 'optional',
    'scope': 'common' },
  // ── AEV fields ─────────────────────────────────────────────────────────────
  { 'key': 'cve_id',
    'label': 'CVE ID',
    'type': 'text',
    '24h': 'optional',
    '72h': 'optional',
    'final': 'optional',
    'scope': 'aev' },
  { 'key': 'euvd_id',
    'label': 'EUVD ID',
    'type': 'text',
    '24h': 'optional',
    '72h': 'optional',
    'final': 'optional',
    'scope': 'aev' },
  { 'key': 'general_information',
    'label': 'General Information',
    'type': 'textarea',
    '24h': 'optional',
    '72h': 'required',
    'final': 'optional',
    'scope': 'aev' },
  { 'key': 'corrective_or_mitigating_measure_available_at',
    'label': 'Date When Corrective or Mitigating Measure Has Been Available',
    'type': 'date',
    '24h': 'optional',
    '72h': 'optional',
    'final': 'required',
    'scope': 'aev' },
  { 'key': 'vulnerability_severity',
    'label': 'Detailed Description of the Severity of the Vulnerability',
    'type': 'textarea',
    '24h': 'optional',
    '72h': 'optional',
    'final': 'required',
    'scope': 'aev' },
  { 'key': 'vulnerability_impact',
    'label': 'Detailed Description of the Impact of the Vulnerability',
    'type': 'textarea',
    '24h': 'optional',
    '72h': 'optional',
    'final': 'required',
    'scope': 'aev' },
  { 'key': 'aev_detected_at',
    'label': 'Date/Time When You Became Aware of the AEV',
    'type': 'datetime-local',
    '24h': 'required',
    '72h': 'optional',
    'final': 'optional',
    'scope': 'aev' },
  { 'key': 'known_or_suspected_malicious_actor',
    'label': 'Malicious Actor That Has Exploited / Is Exploiting the Vulnerability',
    'type': 'text',
    '24h': 'optional',
    '72h': 'optional',
    'final': 'required_if_available',
    'scope': 'aev' },
  { 'key': 'pec',
    'label': 'Particular Exceptional Circumstances (PEC)',
    'type': 'textarea',
    '24h': 'na',
    '72h': 'optional',
    'final': 'na',
    'scope': 'aev' },
  { 'key': 'pec_delay_reason',
    'label': 'PEC Delay Reason',
    'type': 'textarea',
    '24h': 'na',
    '72h': 'optional',
    'final': 'na',
    'scope': 'aev' },
  { 'key': 'further_information',
    'label': 'Please Provide Further Information',
    'type': 'textarea',
    '24h': 'optional',
    '72h': 'optional',
    'final': 'optional',
    'scope': 'aev' },
  // ── SI fields ──────────────────────────────────────────────────────────────
  { 'key': 'suspected_unlawful_or_malicious_acts',
    'label': 'Incident Is Suspected of Unlawful or Malicious Acts',
    'type': 'text',
    '24h': 'required',
    '72h': 'optional',
    'final': 'optional',
    'scope': 'si' },
  { 'key': 'general_incident_information',
    'label': 'General Information About Nature of Incident',
    'type': 'textarea',
    '24h': 'optional',
    '72h': 'required',
    'final': 'optional',
    'scope': 'si' },
  { 'key': 'applied_and_ongoing_mitigation_measures',
    'label': 'Applied and Ongoing Mitigation Measures',
    'type': 'textarea',
    '24h': 'optional',
    '72h': 'optional',
    'final': 'required',
    'scope': 'si' },
  { 'key': 'incident_severity',
    'label': 'Detailed Description of the Severity of the Incident',
    'type': 'textarea',
    '24h': 'optional',
    '72h': 'optional',
    'final': 'required',
    'scope': 'si' },
  { 'key': 'incident_impact',
    'label': 'Detailed Description of the Impact of the Incident',
    'type': 'textarea',
    '24h': 'optional',
    '72h': 'optional',
    'final': 'required',
    'scope': 'si' },
  { 'key': 'likely_threat_or_root_cause',
    'label': 'Type of Threat or Root Cause Likely to Have Triggered the Incident',
    'type': 'textarea',
    '24h': 'optional',
    '72h': 'optional',
    'final': 'required',
    'scope': 'si' },
  { 'key': 'incident_detected_at',
    'label': 'Date/Time When You Became Aware of the Incident',
    'type': 'datetime-local',
    '24h': 'required',
    '72h': 'optional',
    'final': 'optional',
    'scope': 'si' },
  { 'key': 'incident_occurred_at',
    'label': 'Date/Time When the Incident Occurred',
    'type': 'datetime-local',
    '24h': 'optional',
    '72h': 'optional',
    'final': 'optional',
    'scope': 'si' },
  { 'key': 'initial_incident_assessment',
    'label': 'Initial Assessment of the Incident',
    'type': 'textarea',
    '24h': 'optional',
    '72h': 'required',
    'final': 'optional',
    'scope': 'si' },
];
