/* tslint:disable */
/* eslint-disable */
/**
 * OSIDB API
 * REST API autogenerated docs for the OSIDB and its components
 *
 * The version of the OpenAPI document: 4.12.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type {
  AuthTokenCreate200Response,
  AuthTokenCreate200ResponseAllOf,
  AuthTokenRefreshCreate200Response,
  AuthTokenRefreshRetrieve200Response,
  AuthTokenRetrieve200Response,
  TokenObtainPairRequest,
  TokenRefreshRequest,
  TokenVerifyRequest,
} from '../models';

/**
* Takes a set of user credentials and returns an access and refresh JSON web token pair to prove the authentication of those credentials.
* @Path /auth/token
* @Method POST
*/
export type authTokenCreate = TokenObtainPairRequest;
/**
* Takes a refresh type JSON web token and returns an access type JSON web token if the refresh token is valid.
* @Path /auth/token/refresh
* @Method POST
*/
export type authTokenRefreshCreate = TokenRefreshRequest;
/**
* @Path /auth/token/refresh
* @Method GET
*/
/**
* Takes a kerberos ticket and returns an access and refresh JWT pair.
* @Path /auth/token
* @Method GET
*/
/**
* Takes a token and indicates if it is valid.  This view provides no information about a token\'s fitness for a particular use.
* @Path /auth/token/verify
* @Method POST
*/
export type authTokenVerifyCreate = TokenVerifyRequest;

