/* tslint:disable */
/* eslint-disable */
/**
 * OSIDB API
 * REST API autogenerated docs for the OSIDB and its components
 *
 * The version of the OpenAPI document: 4.12.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type {
  AuthTokenCreate200ResponseAllOf,
  CollectorsApiV1StatusRetrieve200Response,
  CollectorsRetrieve200Response,
} from '../models';

/**
* get the overall status of all collectors and the collected data
* @Path /collectors/api/v1/status
* @Method GET
*/
/**
* unauthenticated health check API endpoint
* @Path /collectors/healthy
* @Method GET
*/
/**
* index API endpoint listing available collector API endpoints
* @Path /collectors/
* @Method GET
*/

