/* tslint:disable */
/* eslint-disable */
/**
 * OSIDB API
 * REST API autogenerated docs for the OSIDB and its components
 *
 * The version of the OpenAPI document: 4.12.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type {
  AffectBulkPutRequest,
  AffectCVSSPostRequest,
  AffectCVSSPutRequest,
  AffectCVSSV2PostRequest,
  AffectCVSSV2PutRequest,
  AffectPostRequest,
  AffectRequest,
  AuditRequest,
  AuthTokenCreate200ResponseAllOf,
  FlawAcknowledgmentPostRequest,
  FlawAcknowledgmentPutRequest,
  FlawCVSSPostRequest,
  FlawCVSSPutRequest,
  FlawCVSSV2PostRequest,
  FlawCVSSV2PutRequest,
  FlawCollaboratorPostRequest,
  FlawCommentPostRequest,
  FlawPackageVersionPostRequest,
  FlawPackageVersionPutRequest,
  FlawPostRequest,
  FlawReferencePostRequest,
  FlawReferencePutRequest,
  FlawRequest,
  OsidbApiV1AffectsBulkUpdate200Response,
  OsidbApiV1AffectsCreate201Response,
  OsidbApiV1AffectsCvssScoresCreate201Response,
  OsidbApiV1AffectsCvssScoresList200Response,
  OsidbApiV1AffectsList200Response,
  OsidbApiV1AlertsList200Response,
  OsidbApiV1AlertsRetrieve200Response,
  OsidbApiV1AuditList200Response,
  OsidbApiV1AuditRetrieve200Response,
  OsidbApiV1FlawsAcknowledgmentsCreate201Response,
  OsidbApiV1FlawsAcknowledgmentsList200Response,
  OsidbApiV1FlawsCommentsCreate201Response,
  OsidbApiV1FlawsCommentsList200Response,
  OsidbApiV1FlawsCreate201Response,
  OsidbApiV1FlawsCvssScoresCreate201Response,
  OsidbApiV1FlawsCvssScoresList200Response,
  OsidbApiV1FlawsLabelsCreate201Response,
  OsidbApiV1FlawsLabelsList200Response,
  OsidbApiV1FlawsList200Response,
  OsidbApiV1FlawsPackageVersionsCreate201Response,
  OsidbApiV1FlawsPackageVersionsList200Response,
  OsidbApiV1FlawsReferencesCreate201Response,
  OsidbApiV1FlawsReferencesList200Response,
  OsidbApiV1LabelsList200Response,
  OsidbApiV1LabelsRetrieve200Response,
  OsidbApiV1SchemaRetrieve200Response,
  OsidbApiV1StatusRetrieve200Response,
  OsidbApiV1TrackersCreate201Response,
  OsidbApiV1TrackersList200Response,
  OsidbApiV1TrackersRetrieve200Response,
  OsidbApiV2betaAffectsCvssScoresCreate201Response,
  OsidbApiV2betaAffectsCvssScoresList200Response,
  OsidbApiV2betaFlawsCvssScoresCreate201Response,
  OsidbApiV2betaFlawsCvssScoresList200Response,
  OsidbIntegrationsRetrieve200Response,
  OsidbWhoamiRetrieve200Response,
  PatchedIntegrationTokenPatchRequest,
  RejectRequest,
  TrackerPostRequest,
  TrackerRequest,
} from '../models';

/**
* Bulk create endpoint. Expects a list of dict Affect objects.
* @Path /osidb/api/v1/affects/bulk
* @Method POST
*/
export type osidbApiV1AffectsBulkCreate = Array<AffectPostRequest>;
/**
* Bulk delete endpoint. Expects a list of Affect uuids.
* @Path /osidb/api/v1/affects/bulk
* @Method DELETE
*/
export type osidbApiV1AffectsBulkDestroy = {
}
/**
* Bulk update endpoint. Expects a list of dict Affect objects.
* @Path /osidb/api/v1/affects/bulk
* @Method PUT
*/
export type osidbApiV1AffectsBulkUpdate = Array<AffectBulkPutRequest>;
/**
* @Path /osidb/api/v1/affects
* @Method POST
*/
export type osidbApiV1AffectsCreate = AffectPostRequest;
/**
* @Path /osidb/api/v1/affects/{affect_id}/cvss_scores
* @Method POST
*/
export type osidbApiV1AffectsCvssScoresCreate = AffectCVSSPostRequest;
/**
* Destroy the instance and proxy the delete to Bugzilla.
* @Path /osidb/api/v1/affects/{affect_id}/cvss_scores/{id}
* @Method DELETE
*/
export type osidbApiV1AffectsCvssScoresDestroy = {
}
/**
* @Path /osidb/api/v1/affects/{affect_id}/cvss_scores
* @Method GET
*/
export type osidbApiV1AffectsCvssScoresList = {
    comment: string;
    created_dt: string;
    created_dt__date: string;
    created_dt__date__gte: string;
    created_dt__date__lte: string;
    created_dt__gt: string;
    created_dt__gte: string;
    created_dt__lt: string;
    created_dt__lte: string;
    cvss_version: string;
    exclude_fields: Array<string>;
    include_fields: Array<string>;
    issuer: OsidbApiV1AffectsCvssScoresListIssuerEnum;
    limit: number;
    offset: number;
    score: number;
    updated_dt: string;
    updated_dt__date: string;
    updated_dt__date__gte: string;
    updated_dt__date__lte: string;
    updated_dt__gt: string;
    updated_dt__gte: string;
    updated_dt__lt: string;
    updated_dt__lte: string;
    uuid: string;
    vector: string;
}
/**
* @Path /osidb/api/v1/affects/{affect_id}/cvss_scores/{id}
* @Method GET
*/
export type osidbApiV1AffectsCvssScoresRetrieve = {
    exclude_fields: Array<string>;
    include_fields: Array<string>;
}
/**
* @Path /osidb/api/v1/affects/{affect_id}/cvss_scores/{id}
* @Method PUT
*/
export type osidbApiV1AffectsCvssScoresUpdate = AffectCVSSPutRequest;
/**
* Destroy the instance and proxy the delete to Bugzilla
* @Path /osidb/api/v1/affects/{uuid}
* @Method DELETE
*/
export type osidbApiV1AffectsDestroy = {
}
/**
* @Path /osidb/api/v1/affects
* @Method GET
*/
export type osidbApiV1AffectsList = {
    affectedness: OsidbApiV1AffectsListAffectednessEnum;
    created_dt: string;
    created_dt__date: string;
    created_dt__date__gte: string;
    created_dt__date__lte: string;
    created_dt__gt: string;
    created_dt__gte: string;
    created_dt__lt: string;
    created_dt__lte: string;
    cve_id: string;
    cvss_scores__comment: string;
    cvss_scores__created_dt: string;
    cvss_scores__created_dt__date: string;
    cvss_scores__created_dt__date__gte: string;
    cvss_scores__created_dt__date__lte: string;
    cvss_scores__created_dt__gt: string;
    cvss_scores__created_dt__gte: string;
    cvss_scores__created_dt__lt: string;
    cvss_scores__created_dt__lte: string;
    cvss_scores__cvss_version: string;
    cvss_scores__issuer: OsidbApiV1AffectsListCvssScoresIssuerEnum;
    cvss_scores__score: number;
    cvss_scores__updated_dt: string;
    cvss_scores__updated_dt__date: string;
    cvss_scores__updated_dt__date__gte: string;
    cvss_scores__updated_dt__date__lte: string;
    cvss_scores__updated_dt__gt: string;
    cvss_scores__updated_dt__gte: string;
    cvss_scores__updated_dt__lt: string;
    cvss_scores__updated_dt__lte: string;
    cvss_scores__uuid: string;
    cvss_scores__vector: string;
    embargoed: boolean;
    exclude_fields: Array<string>;
    flaw__components: Array<string>;
    flaw__created_dt: string;
    flaw__created_dt__date: string;
    flaw__created_dt__date__gte: string;
    flaw__created_dt__date__lte: string;
    flaw__created_dt__gt: string;
    flaw__created_dt__gte: string;
    flaw__created_dt__lt: string;
    flaw__created_dt__lte: string;
    flaw__cve_id: string;
    flaw__cwe_id: string;
    flaw__embargoed: boolean;
    flaw__impact: OsidbApiV1AffectsListFlawImpactEnum;
    flaw__reported_dt: string;
    flaw__reported_dt__date: string;
    flaw__reported_dt__date__gte: string;
    flaw__reported_dt__date__lte: string;
    flaw__reported_dt__gt: string;
    flaw__reported_dt__gte: string;
    flaw__reported_dt__lt: string;
    flaw__reported_dt__lte: string;
    flaw__source: OsidbApiV1AffectsListFlawSourceEnum;
    flaw__unembargo_dt: string;
    flaw__updated_dt: string;
    flaw__updated_dt__date: string;
    flaw__updated_dt__date__gte: string;
    flaw__updated_dt__date__lte: string;
    flaw__updated_dt__gt: string;
    flaw__updated_dt__gte: string;
    flaw__updated_dt__lt: string;
    flaw__updated_dt__lte: string;
    flaw__uuid: string;
    flaw__workflow_state: Array<OsidbApiV1AffectsListFlawWorkflowStateEnum>;
    impact: OsidbApiV1AffectsListImpactEnum;
    include_fields: Array<string>;
    include_history: boolean;
    include_meta_attr: Array<string>;
    limit: number;
    offset: number;
    order: Array<OsidbApiV1AffectsListOrderEnum>;
    ps_component: string;
    ps_module: string;
    resolution: OsidbApiV1AffectsListResolutionEnum;
    trackers__created_dt: string;
    trackers__created_dt__date: string;
    trackers__created_dt__date__gte: string;
    trackers__created_dt__date__lte: string;
    trackers__created_dt__gt: string;
    trackers__created_dt__gte: string;
    trackers__created_dt__lt: string;
    trackers__created_dt__lte: string;
    trackers__embargoed: boolean;
    trackers__external_system_id: string;
    trackers__isempty: boolean;
    trackers__ps_update_stream: string;
    trackers__resolution: string;
    trackers__status: string;
    trackers__type: OsidbApiV1AffectsListTrackersTypeEnum;
    trackers__updated_dt: string;
    trackers__updated_dt__date: string;
    trackers__updated_dt__date__gte: string;
    trackers__updated_dt__date__lte: string;
    trackers__updated_dt__gt: string;
    trackers__updated_dt__gte: string;
    trackers__updated_dt__lt: string;
    trackers__updated_dt__lte: string;
    trackers__uuid: string;
    updated_dt: string;
    updated_dt__date: string;
    updated_dt__date__gte: string;
    updated_dt__date__lte: string;
    updated_dt__gt: string;
    updated_dt__gte: string;
    updated_dt__lt: string;
    updated_dt__lte: string;
    uuid: string;
}
/**
* @Path /osidb/api/v1/affects/{uuid}
* @Method GET
*/
export type osidbApiV1AffectsRetrieve = {
    exclude_fields: Array<string>;
    include_fields: Array<string>;
    include_history: boolean;
    include_meta_attr: Array<string>;
}
/**
* @Path /osidb/api/v1/affects/{uuid}
* @Method PUT
*/
export type osidbApiV1AffectsUpdate = AffectRequest;
/**
* List existing alerts for all models.
* @Path /osidb/api/v1/alerts
* @Method GET
*/
export type osidbApiV1AlertsList = {
    alert_type: OsidbApiV1AlertsListAlertTypeEnum;
    exclude_fields: Array<string>;
    include_fields: Array<string>;
    limit: number;
    name: string;
    offset: number;
    parent_model: OsidbApiV1AlertsListParentModelEnum;
    parent_uuid: string;
    uuid: string;
}
/**
* @Path /osidb/api/v1/alerts/{uuid}
* @Method GET
*/
export type osidbApiV1AlertsRetrieve = {
    exclude_fields: Array<string>;
    include_fields: Array<string>;
}
/**
* basic view of audit history events
* @Path /osidb/api/v1/audit
* @Method GET
*/
export type osidbApiV1AuditList = {
    limit: number;
    offset: number;
    pgh_created_at: string;
    pgh_label: string;
    pgh_obj_model: string;
    pgh_slug: string;
}
/**
* basic view of audit history events
* @Path /osidb/api/v1/audit/{pgh_slug}
* @Method GET
*/
export type osidbApiV1AuditRetrieve = {
}
/**
* basic view of audit history events
* @Path /osidb/api/v1/audit/{pgh_slug}
* @Method PUT
*/
export type osidbApiV1AuditUpdate = AuditRequest;
/**
* @Path /osidb/api/v1/flaws/{flaw_id}/acknowledgments
* @Method POST
*/
export type osidbApiV1FlawsAcknowledgmentsCreate = FlawAcknowledgmentPostRequest;
/**
* Destroy the instance and proxy the delete to Bugzilla
* @Path /osidb/api/v1/flaws/{flaw_id}/acknowledgments/{id}
* @Method DELETE
*/
export type osidbApiV1FlawsAcknowledgmentsDestroy = {
}
/**
* @Path /osidb/api/v1/flaws/{flaw_id}/acknowledgments
* @Method GET
*/
export type osidbApiV1FlawsAcknowledgmentsList = {
    affiliation: string;
    created_dt: string;
    created_dt__date: string;
    created_dt__date__gte: string;
    created_dt__date__lte: string;
    created_dt__gt: string;
    created_dt__gte: string;
    created_dt__lt: string;
    created_dt__lte: string;
    exclude_fields: Array<string>;
    from_upstream: boolean;
    include_fields: Array<string>;
    limit: number;
    name: string;
    offset: number;
    updated_dt: string;
    updated_dt__date: string;
    updated_dt__date__gte: string;
    updated_dt__date__lte: string;
    updated_dt__gt: string;
    updated_dt__gte: string;
    updated_dt__lt: string;
    updated_dt__lte: string;
    uuid: string;
}
/**
* @Path /osidb/api/v1/flaws/{flaw_id}/acknowledgments/{id}
* @Method GET
*/
export type osidbApiV1FlawsAcknowledgmentsRetrieve = {
    exclude_fields: Array<string>;
    include_fields: Array<string>;
}
/**
* @Path /osidb/api/v1/flaws/{flaw_id}/acknowledgments/{id}
* @Method PUT
*/
export type osidbApiV1FlawsAcknowledgmentsUpdate = FlawAcknowledgmentPutRequest;
/**
* Create a new comment for a given flaw. Beware that freshly created comments are not guaranteed to keep their original UUIDs, especially if multiple comments are created simultaneously.
* @Path /osidb/api/v1/flaws/{flaw_id}/comments
* @Method POST
*/
export type osidbApiV1FlawsCommentsCreate = FlawCommentPostRequest;
/**
* List existing comments for a given flaw. Beware that freshly created comments are not guaranteed to keep their original UUIDs, especially if multiple comments are created simultaneously.
* @Path /osidb/api/v1/flaws/{flaw_id}/comments
* @Method GET
*/
export type osidbApiV1FlawsCommentsList = {
    creator: string;
    exclude_fields: Array<string>;
    external_system_id: string;
    include_fields: Array<string>;
    limit: number;
    offset: number;
    order: number;
    uuid: string;
}
/**
* Retrieve a single existing comments for a given flaw. Beware that freshly created comments are not guaranteed to keep their original UUIDs, especially if multiple comments are created simultaneously.
* @Path /osidb/api/v1/flaws/{flaw_id}/comments/{comment_id}
* @Method GET
*/
export type osidbApiV1FlawsCommentsRetrieve = {
    exclude_fields: Array<string>;
    include_fields: Array<string>;
}
/**
* @Path /osidb/api/v1/flaws
* @Method POST
*/
export type osidbApiV1FlawsCreate = FlawPostRequest;
/**
* @Path /osidb/api/v1/flaws/{flaw_id}/cvss_scores
* @Method POST
*/
export type osidbApiV1FlawsCvssScoresCreate = FlawCVSSPostRequest;
/**
* Destroy the instance and proxy the delete to Bugzilla
* @Path /osidb/api/v1/flaws/{flaw_id}/cvss_scores/{id}
* @Method DELETE
*/
export type osidbApiV1FlawsCvssScoresDestroy = {
}
/**
* @Path /osidb/api/v1/flaws/{flaw_id}/cvss_scores
* @Method GET
*/
export type osidbApiV1FlawsCvssScoresList = {
    comment: string;
    created_dt: string;
    created_dt__date: string;
    created_dt__date__gte: string;
    created_dt__date__lte: string;
    created_dt__gt: string;
    created_dt__gte: string;
    created_dt__lt: string;
    created_dt__lte: string;
    cvss_version: string;
    exclude_fields: Array<string>;
    include_fields: Array<string>;
    issuer: OsidbApiV1FlawsCvssScoresListIssuerEnum;
    limit: number;
    offset: number;
    score: number;
    updated_dt: string;
    updated_dt__date: string;
    updated_dt__date__gte: string;
    updated_dt__date__lte: string;
    updated_dt__gt: string;
    updated_dt__gte: string;
    updated_dt__lt: string;
    updated_dt__lte: string;
    uuid: string;
    vector: string;
}
/**
* @Path /osidb/api/v1/flaws/{flaw_id}/cvss_scores/{id}
* @Method GET
*/
export type osidbApiV1FlawsCvssScoresRetrieve = {
    exclude_fields: Array<string>;
    include_fields: Array<string>;
}
/**
* @Path /osidb/api/v1/flaws/{flaw_id}/cvss_scores/{id}
* @Method PUT
*/
export type osidbApiV1FlawsCvssScoresUpdate = FlawCVSSPutRequest;
/**
* @Path /osidb/api/v1/flaws/{flaw_id}/labels
* @Method POST
*/
export type osidbApiV1FlawsLabelsCreate = FlawCollaboratorPostRequest;
/**
* @Path /osidb/api/v1/flaws/{flaw_id}/labels/{id}
* @Method DELETE
*/
export type osidbApiV1FlawsLabelsDestroy = {
}
/**
* @Path /osidb/api/v1/flaws/{flaw_id}/labels
* @Method GET
*/
export type osidbApiV1FlawsLabelsList = {
    limit: number;
    offset: number;
}
/**
* @Path /osidb/api/v1/flaws/{flaw_id}/labels/{id}
* @Method GET
*/
export type osidbApiV1FlawsLabelsRetrieve = {
}
/**
* @Path /osidb/api/v1/flaws/{flaw_id}/labels/{id}
* @Method PUT
*/
export type osidbApiV1FlawsLabelsUpdate = FlawCollaboratorPostRequest;
/**
* @Path /osidb/api/v1/flaws
* @Method GET
*/
export type osidbApiV1FlawsList = {
    acknowledgments__affiliation: string;
    acknowledgments__created_dt: string;
    acknowledgments__created_dt__date: string;
    acknowledgments__created_dt__date__gte: string;
    acknowledgments__created_dt__date__lte: string;
    acknowledgments__created_dt__gt: string;
    acknowledgments__created_dt__gte: string;
    acknowledgments__created_dt__lt: string;
    acknowledgments__created_dt__lte: string;
    acknowledgments__from_upstream: boolean;
    acknowledgments__name: string;
    acknowledgments__updated_dt: string;
    acknowledgments__updated_dt__date: string;
    acknowledgments__updated_dt__date__gte: string;
    acknowledgments__updated_dt__date__lte: string;
    acknowledgments__updated_dt__gt: string;
    acknowledgments__updated_dt__gte: string;
    acknowledgments__updated_dt__lt: string;
    acknowledgments__updated_dt__lte: string;
    acknowledgments__uuid: string;
    affects__affectedness: OsidbApiV1FlawsListAffectsAffectednessEnum;
    affects__created_dt: string;
    affects__created_dt__date: string;
    affects__created_dt__date__gte: string;
    affects__created_dt__date__lte: string;
    affects__created_dt__gt: string;
    affects__created_dt__gte: string;
    affects__created_dt__lt: string;
    affects__created_dt__lte: string;
    affects__embargoed: boolean;
    affects__impact: OsidbApiV1FlawsListAffectsImpactEnum;
    affects__ps_component: string;
    affects__ps_module: string;
    affects__resolution: OsidbApiV1FlawsListAffectsResolutionEnum;
    affects__trackers__created_dt: string;
    affects__trackers__created_dt__date: string;
    affects__trackers__created_dt__date__gte: string;
    affects__trackers__created_dt__date__lte: string;
    affects__trackers__created_dt__gt: string;
    affects__trackers__created_dt__gte: string;
    affects__trackers__created_dt__lt: string;
    affects__trackers__created_dt__lte: string;
    affects__trackers__embargoed: boolean;
    affects__trackers__errata__advisory_name: string;
    affects__trackers__errata__et_id: number;
    affects__trackers__errata__shipped_dt: string;
    affects__trackers__errata__shipped_dt__date: string;
    affects__trackers__errata__shipped_dt__date__gte: string;
    affects__trackers__errata__shipped_dt__date__lte: string;
    affects__trackers__errata__shipped_dt__gt: string;
    affects__trackers__errata__shipped_dt__gte: string;
    affects__trackers__errata__shipped_dt__lt: string;
    affects__trackers__errata__shipped_dt__lte: string;
    affects__trackers__external_system_id: string;
    affects__trackers__ps_update_stream: string;
    affects__trackers__resolution: string;
    affects__trackers__status: string;
    affects__trackers__type: OsidbApiV1FlawsListAffectsTrackersTypeEnum;
    affects__trackers__updated_dt: string;
    affects__trackers__updated_dt__date: string;
    affects__trackers__updated_dt__date__gte: string;
    affects__trackers__updated_dt__date__lte: string;
    affects__trackers__updated_dt__gt: string;
    affects__trackers__updated_dt__gte: string;
    affects__trackers__updated_dt__lt: string;
    affects__trackers__updated_dt__lte: string;
    affects__trackers__uuid: string;
    affects__updated_dt: string;
    affects__updated_dt__date: string;
    affects__updated_dt__date__gte: string;
    affects__updated_dt__date__lte: string;
    affects__updated_dt__gt: string;
    affects__updated_dt__gte: string;
    affects__updated_dt__lt: string;
    affects__updated_dt__lte: string;
    affects__uuid: string;
    bz_id: number;
    changed_after: string;
    changed_before: string;
    comment_zero: string;
    components: Array<string>;
    created_dt: string;
    created_dt__date: string;
    created_dt__date__gte: string;
    created_dt__date__lte: string;
    created_dt__gt: string;
    created_dt__gte: string;
    created_dt__lt: string;
    created_dt__lte: string;
    cve_description: string;
    cve_description__isempty: boolean;
    cve_id: Array<string>;
    cve_id__isempty: boolean;
    cvss2_nist__isempty: boolean;
    cvss2_rh__isempty: boolean;
    cvss3_nist__isempty: boolean;
    cvss3_rh__isempty: boolean;
    cvss4_nist__isempty: boolean;
    cvss4_rh__isempty: boolean;
    cvss_scores__comment: string;
    cvss_scores__created_dt: string;
    cvss_scores__created_dt__date: string;
    cvss_scores__created_dt__date__gte: string;
    cvss_scores__created_dt__date__lte: string;
    cvss_scores__created_dt__gt: string;
    cvss_scores__created_dt__gte: string;
    cvss_scores__created_dt__lt: string;
    cvss_scores__created_dt__lte: string;
    cvss_scores__cvss_version: string;
    cvss_scores__issuer: OsidbApiV1FlawsListCvssScoresIssuerEnum;
    cvss_scores__score: number;
    cvss_scores__updated_dt: string;
    cvss_scores__updated_dt__date: string;
    cvss_scores__updated_dt__date__gte: string;
    cvss_scores__updated_dt__date__lte: string;
    cvss_scores__updated_dt__gt: string;
    cvss_scores__updated_dt__gte: string;
    cvss_scores__updated_dt__lt: string;
    cvss_scores__updated_dt__lte: string;
    cvss_scores__uuid: string;
    cvss_scores__vector: string;
    cwe_id: string;
    cwe_id__isempty: boolean;
    embargoed: boolean;
    exclude_fields: Array<string>;
    impact: OsidbApiV1FlawsListImpactEnum;
    include_fields: Array<string>;
    include_history: boolean;
    include_meta_attr: Array<string>;
    limit: number;
    major_incident_start_dt: string;
    major_incident_start_dt__date: string;
    major_incident_start_dt__date__gte: string;
    major_incident_start_dt__date__lte: string;
    major_incident_start_dt__gt: string;
    major_incident_start_dt__gte: string;
    major_incident_start_dt__lt: string;
    major_incident_start_dt__lte: string;
    major_incident_state: OsidbApiV1FlawsListMajorIncidentStateEnum;
    mitigation__isempty: boolean;
    nist_cvss_validation: OsidbApiV1FlawsListNistCvssValidationEnum;
    offset: number;
    order: Array<OsidbApiV1FlawsListOrderEnum>;
    owner: string;
    owner__isempty: boolean;
    query: string;
    references__created_dt: string;
    references__created_dt__date: string;
    references__created_dt__date__gte: string;
    references__created_dt__date__lte: string;
    references__created_dt__gt: string;
    references__created_dt__gte: string;
    references__created_dt__lt: string;
    references__created_dt__lte: string;
    references__description: string;
    references__type: OsidbApiV1FlawsListReferencesTypeEnum;
    references__updated_dt: string;
    references__updated_dt__date: string;
    references__updated_dt__date__gte: string;
    references__updated_dt__date__lte: string;
    references__updated_dt__gt: string;
    references__updated_dt__gte: string;
    references__updated_dt__lt: string;
    references__updated_dt__lte: string;
    references__url: string;
    references__uuid: string;
    reported_dt: string;
    reported_dt__date: string;
    reported_dt__date__gte: string;
    reported_dt__date__lte: string;
    reported_dt__gt: string;
    reported_dt__gte: string;
    reported_dt__lt: string;
    reported_dt__lte: string;
    requires_cve_description: OsidbApiV1FlawsListRequiresCveDescriptionEnum;
    search: string;
    source: OsidbApiV1FlawsListSourceEnum;
    statement: string;
    statement__isempty: boolean;
    team_id: string;
    title: string;
    tracker_ids: Array<string>;
    unembargo_dt: string;
    updated_dt: string;
    updated_dt__date: string;
    updated_dt__date__gte: string;
    updated_dt__date__lte: string;
    updated_dt__gt: string;
    updated_dt__gte: string;
    updated_dt__lt: string;
    updated_dt__lte: string;
    uuid: string;
    workflow_state: Array<OsidbApiV1FlawsListWorkflowStateEnum>;
}
/**
* @Path /osidb/api/v1/flaws/{flaw_id}/package_versions
* @Method POST
*/
export type osidbApiV1FlawsPackageVersionsCreate = FlawPackageVersionPostRequest;
/**
* Destroy the instance and proxy the delete to Bugzilla
* @Path /osidb/api/v1/flaws/{flaw_id}/package_versions/{id}
* @Method DELETE
*/
export type osidbApiV1FlawsPackageVersionsDestroy = {
}
/**
* @Path /osidb/api/v1/flaws/{flaw_id}/package_versions
* @Method GET
*/
export type osidbApiV1FlawsPackageVersionsList = {
    created_dt: string;
    created_dt__date: string;
    created_dt__date__gte: string;
    created_dt__date__lte: string;
    created_dt__gt: string;
    created_dt__gte: string;
    created_dt__lt: string;
    created_dt__lte: string;
    exclude_fields: Array<string>;
    include_fields: Array<string>;
    limit: number;
    offset: number;
    package: string;
    updated_dt: string;
    updated_dt__date: string;
    updated_dt__date__gte: string;
    updated_dt__date__lte: string;
    updated_dt__gt: string;
    updated_dt__gte: string;
    updated_dt__lt: string;
    updated_dt__lte: string;
    uuid: string;
    versions__version: string;
}
/**
* @Path /osidb/api/v1/flaws/{flaw_id}/package_versions/{id}
* @Method GET
*/
export type osidbApiV1FlawsPackageVersionsRetrieve = {
    exclude_fields: Array<string>;
    include_fields: Array<string>;
}
/**
* @Path /osidb/api/v1/flaws/{flaw_id}/package_versions/{id}
* @Method PUT
*/
export type osidbApiV1FlawsPackageVersionsUpdate = FlawPackageVersionPutRequest;
/**
* workflow promotion API endpoint  try to adjust workflow classification of flaw to the next state available return its workflow:state classification or errors if not possible to promote
* @Path /osidb/api/v1/flaws/{flaw_id}/promote
* @Method POST
*/
export type osidbApiV1FlawsPromoteCreate = {
}
/**
* @Path /osidb/api/v1/flaws/{flaw_id}/references
* @Method POST
*/
export type osidbApiV1FlawsReferencesCreate = FlawReferencePostRequest;
/**
* Destroy the instance and proxy the delete to Bugzilla
* @Path /osidb/api/v1/flaws/{flaw_id}/references/{id}
* @Method DELETE
*/
export type osidbApiV1FlawsReferencesDestroy = {
}
/**
* @Path /osidb/api/v1/flaws/{flaw_id}/references
* @Method GET
*/
export type osidbApiV1FlawsReferencesList = {
    created_dt: string;
    created_dt__date: string;
    created_dt__date__gte: string;
    created_dt__date__lte: string;
    created_dt__gt: string;
    created_dt__gte: string;
    created_dt__lt: string;
    created_dt__lte: string;
    description: string;
    exclude_fields: Array<string>;
    include_fields: Array<string>;
    limit: number;
    offset: number;
    type: OsidbApiV1FlawsReferencesListTypeEnum;
    updated_dt: string;
    updated_dt__date: string;
    updated_dt__date__gte: string;
    updated_dt__date__lte: string;
    updated_dt__gt: string;
    updated_dt__gte: string;
    updated_dt__lt: string;
    updated_dt__lte: string;
    url: string;
    uuid: string;
}
/**
* @Path /osidb/api/v1/flaws/{flaw_id}/references/{id}
* @Method GET
*/
export type osidbApiV1FlawsReferencesRetrieve = {
    exclude_fields: Array<string>;
    include_fields: Array<string>;
}
/**
* @Path /osidb/api/v1/flaws/{flaw_id}/references/{id}
* @Method PUT
*/
export type osidbApiV1FlawsReferencesUpdate = FlawReferencePutRequest;
/**
* workflow promotion API endpoint  try to reject a flaw / task
* @Path /osidb/api/v1/flaws/{flaw_id}/reject
* @Method POST
*/
export type osidbApiV1FlawsRejectCreate = RejectRequest;
/**
* @Path /osidb/api/v1/flaws/{id}
* @Method GET
*/
export type osidbApiV1FlawsRetrieve = {
    exclude_fields: Array<string>;
    include_fields: Array<string>;
    include_history: boolean;
    include_meta_attr: Array<string>;
    query: string;
    tracker_ids: Array<string>;
}
/**
* @Path /osidb/api/v1/flaws/{id}
* @Method PUT
*/
export type osidbApiV1FlawsUpdate = FlawRequest;
/**
* @Path /osidb/api/v1/labels
* @Method GET
*/
export type osidbApiV1LabelsList = {
    limit: number;
    offset: number;
}
/**
* @Path /osidb/api/v1/labels/{uuid}
* @Method GET
*/
export type osidbApiV1LabelsRetrieve = {
}
/**
* HTTP get /manifest
* @Path /osidb/api/v1/manifest
* @Method GET
*/
/**
* OpenApi3 schema for this API. Format can be selected via content negotiation.  - YAML: application/vnd.oai.openapi - JSON: application/vnd.oai.openapi+json
* @Path /osidb/api/v1/schema/
* @Method GET
*/
export type osidbApiV1SchemaRetrieve = {
    format: OsidbApiV1SchemaRetrieveFormatEnum;
    lang: OsidbApiV1SchemaRetrieveLangEnum;
}
/**
* HTTP get /status
* @Path /osidb/api/v1/status
* @Method GET
*/
/**
* @Path /osidb/api/v1/trackers
* @Method POST
*/
export type osidbApiV1TrackersCreate = TrackerPostRequest;
/**
* @Path /osidb/api/v1/trackers
* @Method GET
*/
export type osidbApiV1TrackersList = {
    affects__affectedness: OsidbApiV1TrackersListAffectsAffectednessEnum;
    affects__created_dt: string;
    affects__created_dt__date: string;
    affects__created_dt__date__gte: string;
    affects__created_dt__date__lte: string;
    affects__created_dt__gt: string;
    affects__created_dt__gte: string;
    affects__created_dt__lt: string;
    affects__created_dt__lte: string;
    affects__embargoed: boolean;
    affects__flaw__components: Array<string>;
    affects__flaw__created_dt: string;
    affects__flaw__created_dt__date: string;
    affects__flaw__created_dt__date__gte: string;
    affects__flaw__created_dt__date__lte: string;
    affects__flaw__created_dt__gt: string;
    affects__flaw__created_dt__gte: string;
    affects__flaw__created_dt__lt: string;
    affects__flaw__created_dt__lte: string;
    affects__flaw__cve_id: string;
    affects__flaw__cwe_id: string;
    affects__flaw__embargoed: boolean;
    affects__flaw__impact: OsidbApiV1TrackersListAffectsFlawImpactEnum;
    affects__flaw__reported_dt: string;
    affects__flaw__reported_dt__date: string;
    affects__flaw__reported_dt__date__gte: string;
    affects__flaw__reported_dt__date__lte: string;
    affects__flaw__reported_dt__gt: string;
    affects__flaw__reported_dt__gte: string;
    affects__flaw__reported_dt__lt: string;
    affects__flaw__reported_dt__lte: string;
    affects__flaw__source: OsidbApiV1TrackersListAffectsFlawSourceEnum;
    affects__flaw__unembargo_dt: string;
    affects__flaw__updated_dt: string;
    affects__flaw__updated_dt__date: string;
    affects__flaw__updated_dt__date__gte: string;
    affects__flaw__updated_dt__date__lte: string;
    affects__flaw__updated_dt__gt: string;
    affects__flaw__updated_dt__gte: string;
    affects__flaw__updated_dt__lt: string;
    affects__flaw__updated_dt__lte: string;
    affects__flaw__uuid: string;
    affects__impact: OsidbApiV1TrackersListAffectsImpactEnum;
    affects__ps_component: string;
    affects__ps_module: string;
    affects__resolution: OsidbApiV1TrackersListAffectsResolutionEnum;
    affects__updated_dt: string;
    affects__updated_dt__date: string;
    affects__updated_dt__date__gte: string;
    affects__updated_dt__date__lte: string;
    affects__updated_dt__gt: string;
    affects__updated_dt__gte: string;
    affects__updated_dt__lt: string;
    affects__updated_dt__lte: string;
    affects__uuid: string;
    created_dt: string;
    created_dt__date: string;
    created_dt__date__gte: string;
    created_dt__date__lte: string;
    created_dt__gt: string;
    created_dt__gte: string;
    created_dt__lt: string;
    created_dt__lte: string;
    cve_id: string;
    embargoed: boolean;
    exclude_fields: Array<string>;
    external_system_id: string;
    include_fields: Array<string>;
    include_meta_attr: Array<string>;
    limit: number;
    offset: number;
    order: Array<OsidbApiV1TrackersListOrderEnum>;
    ps_update_stream: string;
    resolution: string;
    status: string;
    type: OsidbApiV1TrackersListTypeEnum;
    updated_dt: string;
    updated_dt__date: string;
    updated_dt__date__gte: string;
    updated_dt__date__lte: string;
    updated_dt__gt: string;
    updated_dt__gte: string;
    updated_dt__lt: string;
    updated_dt__lte: string;
    uuid: string;
}
/**
* @Path /osidb/api/v1/trackers/{uuid}
* @Method GET
*/
export type osidbApiV1TrackersRetrieve = {
    exclude_fields: Array<string>;
    include_fields: Array<string>;
    include_meta_attr: Array<string>;
}
/**
* @Path /osidb/api/v1/trackers/{uuid}
* @Method PUT
*/
export type osidbApiV1TrackersUpdate = TrackerRequest;
/**
* @Path /osidb/api/v2beta/affects/{affect_id}/cvss-scores
* @Method POST
*/
export type osidbApiV2betaAffectsCvssScoresCreate = AffectCVSSV2PostRequest;
/**
* @Path /osidb/api/v2beta/affects/{affect_id}/cvss-scores/{id}
* @Method DELETE
*/
export type osidbApiV2betaAffectsCvssScoresDestroy = {
}
/**
* @Path /osidb/api/v2beta/affects/{affect_id}/cvss-scores
* @Method GET
*/
export type osidbApiV2betaAffectsCvssScoresList = {
    comment: string;
    created_dt: string;
    created_dt__date: string;
    created_dt__date__gte: string;
    created_dt__date__lte: string;
    created_dt__gt: string;
    created_dt__gte: string;
    created_dt__lt: string;
    created_dt__lte: string;
    cvss_version: string;
    exclude_fields: Array<string>;
    include_fields: Array<string>;
    issuer: OsidbApiV2betaAffectsCvssScoresListIssuerEnum;
    limit: number;
    offset: number;
    score: number;
    updated_dt: string;
    updated_dt__date: string;
    updated_dt__date__gte: string;
    updated_dt__date__lte: string;
    updated_dt__gt: string;
    updated_dt__gte: string;
    updated_dt__lt: string;
    updated_dt__lte: string;
    uuid: string;
    vector: string;
}
/**
* @Path /osidb/api/v2beta/affects/{affect_id}/cvss-scores/{id}
* @Method GET
*/
export type osidbApiV2betaAffectsCvssScoresRetrieve = {
    exclude_fields: Array<string>;
    include_fields: Array<string>;
}
/**
* @Path /osidb/api/v2beta/affects/{affect_id}/cvss-scores/{id}
* @Method PUT
*/
export type osidbApiV2betaAffectsCvssScoresUpdate = AffectCVSSV2PutRequest;
/**
* @Path /osidb/api/v2beta/flaws/{flaw_id}/cvss-scores
* @Method POST
*/
export type osidbApiV2betaFlawsCvssScoresCreate = FlawCVSSV2PostRequest;
/**
* Destroy the instance and proxy the delete to Bugzilla
* @Path /osidb/api/v2beta/flaws/{flaw_id}/cvss-scores/{id}
* @Method DELETE
*/
export type osidbApiV2betaFlawsCvssScoresDestroy = {
}
/**
* @Path /osidb/api/v2beta/flaws/{flaw_id}/cvss-scores
* @Method GET
*/
export type osidbApiV2betaFlawsCvssScoresList = {
    comment: string;
    created_dt: string;
    created_dt__date: string;
    created_dt__date__gte: string;
    created_dt__date__lte: string;
    created_dt__gt: string;
    created_dt__gte: string;
    created_dt__lt: string;
    created_dt__lte: string;
    cvss_version: string;
    exclude_fields: Array<string>;
    include_fields: Array<string>;
    issuer: OsidbApiV2betaFlawsCvssScoresListIssuerEnum;
    limit: number;
    offset: number;
    score: number;
    updated_dt: string;
    updated_dt__date: string;
    updated_dt__date__gte: string;
    updated_dt__date__lte: string;
    updated_dt__gt: string;
    updated_dt__gte: string;
    updated_dt__lt: string;
    updated_dt__lte: string;
    uuid: string;
    vector: string;
}
/**
* @Path /osidb/api/v2beta/flaws/{flaw_id}/cvss-scores/{id}
* @Method GET
*/
export type osidbApiV2betaFlawsCvssScoresRetrieve = {
    exclude_fields: Array<string>;
    include_fields: Array<string>;
}
/**
* @Path /osidb/api/v2beta/flaws/{flaw_id}/cvss-scores/{id}
* @Method PUT
*/
export type osidbApiV2betaFlawsCvssScoresUpdate = FlawCVSSV2PutRequest;
/**
* unauthenticated view providing healthcheck on osidb service
* @Path /osidb/healthy
* @Method GET
*/
/**
* Set third-party integration tokens for the current user.
* @Path /osidb/integrations
* @Method PATCH
*/
export type osidbIntegrationsPartialUpdate = PatchedIntegrationTokenPatchRequest;
/**
* Set third-party integration tokens for the current user.
* @Path /osidb/integrations
* @Method GET
*/
/**
* View that provides information about the currently logged-in user
* @Path /osidb/whoami
* @Method GET
*/


export const OsidbApiV1AffectsCvssScoresListIssuerEnum = {
    Cisa: 'CISA',
    Cveorg: 'CVEORG',
    Nist: 'NIST',
    Osv: 'OSV',
    Rh: 'RH'
} as const;
export type OsidbApiV1AffectsCvssScoresListIssuerEnum = typeof OsidbApiV1AffectsCvssScoresListIssuerEnum[keyof typeof OsidbApiV1AffectsCvssScoresListIssuerEnum];

export const OsidbApiV1AffectsListAffectednessEnum = {
    Empty: '',
    Affected: 'AFFECTED',
    New: 'NEW',
    Notaffected: 'NOTAFFECTED'
} as const;
export type OsidbApiV1AffectsListAffectednessEnum = typeof OsidbApiV1AffectsListAffectednessEnum[keyof typeof OsidbApiV1AffectsListAffectednessEnum];

export const OsidbApiV1AffectsListCvssScoresIssuerEnum = {
    Cisa: 'CISA',
    Cveorg: 'CVEORG',
    Nist: 'NIST',
    Osv: 'OSV',
    Rh: 'RH'
} as const;
export type OsidbApiV1AffectsListCvssScoresIssuerEnum = typeof OsidbApiV1AffectsListCvssScoresIssuerEnum[keyof typeof OsidbApiV1AffectsListCvssScoresIssuerEnum];

export const OsidbApiV1AffectsListFlawImpactEnum = {
    Empty: '',
    Critical: 'CRITICAL',
    Important: 'IMPORTANT',
    Low: 'LOW',
    Moderate: 'MODERATE'
} as const;
export type OsidbApiV1AffectsListFlawImpactEnum = typeof OsidbApiV1AffectsListFlawImpactEnum[keyof typeof OsidbApiV1AffectsListFlawImpactEnum];

export const OsidbApiV1AffectsListFlawSourceEnum = {
    Empty: '',
    Adobe: 'ADOBE',
    Apple: 'APPLE',
    Asf: 'ASF',
    Bind: 'BIND',
    Bk: 'BK',
    Bugtraq: 'BUGTRAQ',
    Bugzilla: 'BUGZILLA',
    Cert: 'CERT',
    Certifi: 'CERTIFI',
    Corelabs: 'CORELABS',
    Customer: 'CUSTOMER',
    Cve: 'CVE',
    Cveorg: 'CVEORG',
    Dailydave: 'DAILYDAVE',
    Debian: 'DEBIAN',
    Distros: 'DISTROS',
    Fedora: 'FEDORA',
    Fetchmail: 'FETCHMAIL',
    Freedesktop: 'FREEDESKTOP',
    Freeradius: 'FREERADIUS',
    Frsirt: 'FRSIRT',
    Fulldisclosure: 'FULLDISCLOSURE',
    Gaim: 'GAIM',
    Gentoo: 'GENTOO',
    Gentoobz: 'GENTOOBZ',
    Git: 'GIT',
    Gnome: 'GNOME',
    Gnupg: 'GNUPG',
    Google: 'GOOGLE',
    Hp: 'HP',
    HwVendor: 'HW_VENDOR',
    Ibm: 'IBM',
    Idefense: 'IDEFENSE',
    Internet: 'INTERNET',
    Isc: 'ISC',
    Isec: 'ISEC',
    It: 'IT',
    Jboss: 'JBOSS',
    Jpcert: 'JPCERT',
    Kernelbugzilla: 'KERNELBUGZILLA',
    Kernelsec: 'KERNELSEC',
    Lkml: 'LKML',
    Lwn: 'LWN',
    Macromedia: 'MACROMEDIA',
    Mageia: 'MAGEIA',
    Mailinglist: 'MAILINGLIST',
    Milw0Rm: 'MILW0RM',
    Mit: 'MIT',
    Mitre: 'MITRE',
    Mozilla: 'MOZILLA',
    Muttdev: 'MUTTDEV',
    Netdev: 'NETDEV',
    Niscc: 'NISCC',
    Nvd: 'NVD',
    Ocert: 'OCERT',
    Openoffice: 'OPENOFFICE',
    Openssl: 'OPENSSL',
    Opensuse: 'OPENSUSE',
    Oracle: 'ORACLE',
    Oss: 'OSS',
    Osssecurity: 'OSSSECURITY',
    Osv: 'OSV',
    Php: 'PHP',
    Pidgin: 'PIDGIN',
    Postgresql: 'POSTGRESQL',
    Press: 'PRESS',
    Real: 'REAL',
    Redhat: 'REDHAT',
    Researcher: 'RESEARCHER',
    Rt: 'RT',
    Samba: 'SAMBA',
    Secalert: 'SECALERT',
    Secunia: 'SECUNIA',
    Securityfocus: 'SECURITYFOCUS',
    Sko: 'SKO',
    Squid: 'SQUID',
    Squirrelmail: 'SQUIRRELMAIL',
    Sun: 'SUN',
    Sunsolve: 'SUNSOLVE',
    Suse: 'SUSE',
    Twitter: 'TWITTER',
    Ubuntu: 'UBUNTU',
    Upstream: 'UPSTREAM',
    Vendorsec: 'VENDORSEC',
    Vulnwatch: 'VULNWATCH',
    Wireshark: 'WIRESHARK',
    Xchat: 'XCHAT',
    Xen: 'XEN',
    Xpdf: 'XPDF'
} as const;
export type OsidbApiV1AffectsListFlawSourceEnum = typeof OsidbApiV1AffectsListFlawSourceEnum[keyof typeof OsidbApiV1AffectsListFlawSourceEnum];

export const OsidbApiV1AffectsListFlawWorkflowStateEnum = {
    Empty: '',
    Done: 'DONE',
    New: 'NEW',
    PreSecondaryAssessment: 'PRE_SECONDARY_ASSESSMENT',
    Rejected: 'REJECTED',
    SecondaryAssessment: 'SECONDARY_ASSESSMENT',
    Triage: 'TRIAGE'
} as const;
export type OsidbApiV1AffectsListFlawWorkflowStateEnum = typeof OsidbApiV1AffectsListFlawWorkflowStateEnum[keyof typeof OsidbApiV1AffectsListFlawWorkflowStateEnum];

export const OsidbApiV1AffectsListImpactEnum = {
    Empty: '',
    Critical: 'CRITICAL',
    Important: 'IMPORTANT',
    Low: 'LOW',
    Moderate: 'MODERATE'
} as const;
export type OsidbApiV1AffectsListImpactEnum = typeof OsidbApiV1AffectsListImpactEnum[keyof typeof OsidbApiV1AffectsListImpactEnum];

export const OsidbApiV1AffectsListOrderEnum = {
    Affectedness: '-affectedness',
    CreatedDt: '-created_dt',
    CveId: '-cve_id',
    CvssScoresComment: '-cvss_scores__comment',
    CvssScoresCreatedDt: '-cvss_scores__created_dt',
    CvssScoresCvssVersion: '-cvss_scores__cvss_version',
    CvssScoresIssuer: '-cvss_scores__issuer',
    CvssScoresScore: '-cvss_scores__score',
    CvssScoresUpdatedDt: '-cvss_scores__updated_dt',
    CvssScoresUuid: '-cvss_scores__uuid',
    CvssScoresVector: '-cvss_scores__vector',
    Embargoed: '-embargoed',
    FlawComponents: '-flaw__components',
    FlawCreatedDt: '-flaw__created_dt',
    FlawCveId: '-flaw__cve_id',
    FlawCweId: '-flaw__cwe_id',
    FlawEmbargoed: '-flaw__embargoed',
    FlawImpact: '-flaw__impact',
    FlawReportedDt: '-flaw__reported_dt',
    FlawSource: '-flaw__source',
    FlawUnembargoDt: '-flaw__unembargo_dt',
    FlawUpdatedDt: '-flaw__updated_dt',
    FlawUuid: '-flaw__uuid',
    Impact: '-impact',
    PsComponent: '-ps_component',
    PsModule: '-ps_module',
    Resolution: '-resolution',
    TrackersCreatedDt: '-trackers__created_dt',
    TrackersEmbargoed: '-trackers__embargoed',
    TrackersExternalSystemId: '-trackers__external_system_id',
    TrackersPsUpdateStream: '-trackers__ps_update_stream',
    TrackersResolution: '-trackers__resolution',
    TrackersStatus: '-trackers__status',
    TrackersType: '-trackers__type',
    TrackersUpdatedDt: '-trackers__updated_dt',
    TrackersUuid: '-trackers__uuid',
    UpdatedDt: '-updated_dt',
    Uuid: '-uuid',
    Affectedness: 'affectedness',
    CreatedDt: 'created_dt',
    CveId: 'cve_id',
    CvssScoresComment: 'cvss_scores__comment',
    CvssScoresCreatedDt: 'cvss_scores__created_dt',
    CvssScoresCvssVersion: 'cvss_scores__cvss_version',
    CvssScoresIssuer: 'cvss_scores__issuer',
    CvssScoresScore: 'cvss_scores__score',
    CvssScoresUpdatedDt: 'cvss_scores__updated_dt',
    CvssScoresUuid: 'cvss_scores__uuid',
    CvssScoresVector: 'cvss_scores__vector',
    Embargoed: 'embargoed',
    FlawComponents: 'flaw__components',
    FlawCreatedDt: 'flaw__created_dt',
    FlawCveId: 'flaw__cve_id',
    FlawCweId: 'flaw__cwe_id',
    FlawEmbargoed: 'flaw__embargoed',
    FlawImpact: 'flaw__impact',
    FlawReportedDt: 'flaw__reported_dt',
    FlawSource: 'flaw__source',
    FlawUnembargoDt: 'flaw__unembargo_dt',
    FlawUpdatedDt: 'flaw__updated_dt',
    FlawUuid: 'flaw__uuid',
    Impact: 'impact',
    PsComponent: 'ps_component',
    PsModule: 'ps_module',
    Resolution: 'resolution',
    TrackersCreatedDt: 'trackers__created_dt',
    TrackersEmbargoed: 'trackers__embargoed',
    TrackersExternalSystemId: 'trackers__external_system_id',
    TrackersPsUpdateStream: 'trackers__ps_update_stream',
    TrackersResolution: 'trackers__resolution',
    TrackersStatus: 'trackers__status',
    TrackersType: 'trackers__type',
    TrackersUpdatedDt: 'trackers__updated_dt',
    TrackersUuid: 'trackers__uuid',
    UpdatedDt: 'updated_dt',
    Uuid: 'uuid'
} as const;
export type OsidbApiV1AffectsListOrderEnum = typeof OsidbApiV1AffectsListOrderEnum[keyof typeof OsidbApiV1AffectsListOrderEnum];

export const OsidbApiV1AffectsListResolutionEnum = {
    Empty: '',
    Defer: 'DEFER',
    Delegated: 'DELEGATED',
    Fix: 'FIX',
    Ooss: 'OOSS',
    Wontfix: 'WONTFIX',
    Wontreport: 'WONTREPORT'
} as const;
export type OsidbApiV1AffectsListResolutionEnum = typeof OsidbApiV1AffectsListResolutionEnum[keyof typeof OsidbApiV1AffectsListResolutionEnum];

export const OsidbApiV1AffectsListTrackersTypeEnum = {
    Bugzilla: 'BUGZILLA',
    Jira: 'JIRA'
} as const;
export type OsidbApiV1AffectsListTrackersTypeEnum = typeof OsidbApiV1AffectsListTrackersTypeEnum[keyof typeof OsidbApiV1AffectsListTrackersTypeEnum];

export const OsidbApiV1AlertsListAlertTypeEnum = {
    Error: 'ERROR',
    Warning: 'WARNING'
} as const;
export type OsidbApiV1AlertsListAlertTypeEnum = typeof OsidbApiV1AlertsListAlertTypeEnum[keyof typeof OsidbApiV1AlertsListAlertTypeEnum];

export const OsidbApiV1AlertsListParentModelEnum = {
    Affect: 'affect',
    Affectcvss: 'affectcvss',
    Flaw: 'flaw',
    Flawacknowledgment: 'flawacknowledgment',
    Flawcomment: 'flawcomment',
    Flawcvss: 'flawcvss',
    Flawreference: 'flawreference',
    Package: 'package',
    Snippet: 'snippet',
    Tracker: 'tracker'
} as const;
export type OsidbApiV1AlertsListParentModelEnum = typeof OsidbApiV1AlertsListParentModelEnum[keyof typeof OsidbApiV1AlertsListParentModelEnum];

export const OsidbApiV1FlawsCvssScoresListIssuerEnum = {
    Cisa: 'CISA',
    Cveorg: 'CVEORG',
    Nist: 'NIST',
    Osv: 'OSV',
    Rh: 'RH'
} as const;
export type OsidbApiV1FlawsCvssScoresListIssuerEnum = typeof OsidbApiV1FlawsCvssScoresListIssuerEnum[keyof typeof OsidbApiV1FlawsCvssScoresListIssuerEnum];

export const OsidbApiV1FlawsListAffectsAffectednessEnum = {
    Empty: '',
    Affected: 'AFFECTED',
    New: 'NEW',
    Notaffected: 'NOTAFFECTED'
} as const;
export type OsidbApiV1FlawsListAffectsAffectednessEnum = typeof OsidbApiV1FlawsListAffectsAffectednessEnum[keyof typeof OsidbApiV1FlawsListAffectsAffectednessEnum];

export const OsidbApiV1FlawsListAffectsImpactEnum = {
    Empty: '',
    Critical: 'CRITICAL',
    Important: 'IMPORTANT',
    Low: 'LOW',
    Moderate: 'MODERATE'
} as const;
export type OsidbApiV1FlawsListAffectsImpactEnum = typeof OsidbApiV1FlawsListAffectsImpactEnum[keyof typeof OsidbApiV1FlawsListAffectsImpactEnum];

export const OsidbApiV1FlawsListAffectsResolutionEnum = {
    Empty: '',
    Defer: 'DEFER',
    Delegated: 'DELEGATED',
    Fix: 'FIX',
    Ooss: 'OOSS',
    Wontfix: 'WONTFIX',
    Wontreport: 'WONTREPORT'
} as const;
export type OsidbApiV1FlawsListAffectsResolutionEnum = typeof OsidbApiV1FlawsListAffectsResolutionEnum[keyof typeof OsidbApiV1FlawsListAffectsResolutionEnum];

export const OsidbApiV1FlawsListAffectsTrackersTypeEnum = {
    Bugzilla: 'BUGZILLA',
    Jira: 'JIRA'
} as const;
export type OsidbApiV1FlawsListAffectsTrackersTypeEnum = typeof OsidbApiV1FlawsListAffectsTrackersTypeEnum[keyof typeof OsidbApiV1FlawsListAffectsTrackersTypeEnum];

export const OsidbApiV1FlawsListCvssScoresIssuerEnum = {
    Cisa: 'CISA',
    Cveorg: 'CVEORG',
    Nist: 'NIST',
    Osv: 'OSV',
    Rh: 'RH'
} as const;
export type OsidbApiV1FlawsListCvssScoresIssuerEnum = typeof OsidbApiV1FlawsListCvssScoresIssuerEnum[keyof typeof OsidbApiV1FlawsListCvssScoresIssuerEnum];

export const OsidbApiV1FlawsListImpactEnum = {
    Empty: '',
    Critical: 'CRITICAL',
    Important: 'IMPORTANT',
    Low: 'LOW',
    Moderate: 'MODERATE'
} as const;
export type OsidbApiV1FlawsListImpactEnum = typeof OsidbApiV1FlawsListImpactEnum[keyof typeof OsidbApiV1FlawsListImpactEnum];

export const OsidbApiV1FlawsListMajorIncidentStateEnum = {
    Empty: '',
    Approved: 'APPROVED',
    CisaApproved: 'CISA_APPROVED',
    Invalid: 'INVALID',
    Minor: 'MINOR',
    Rejected: 'REJECTED',
    Requested: 'REQUESTED',
    ZeroDay: 'ZERO_DAY'
} as const;
export type OsidbApiV1FlawsListMajorIncidentStateEnum = typeof OsidbApiV1FlawsListMajorIncidentStateEnum[keyof typeof OsidbApiV1FlawsListMajorIncidentStateEnum];

export const OsidbApiV1FlawsListNistCvssValidationEnum = {
    Empty: '',
    Approved: 'APPROVED',
    Rejected: 'REJECTED',
    Requested: 'REQUESTED'
} as const;
export type OsidbApiV1FlawsListNistCvssValidationEnum = typeof OsidbApiV1FlawsListNistCvssValidationEnum[keyof typeof OsidbApiV1FlawsListNistCvssValidationEnum];

export const OsidbApiV1FlawsListOrderEnum = {
    AcknowledgmentsAffiliation: '-acknowledgments__affiliation',
    AcknowledgmentsCreatedDt: '-acknowledgments__created_dt',
    AcknowledgmentsFromUpstream: '-acknowledgments__from_upstream',
    AcknowledgmentsName: '-acknowledgments__name',
    AcknowledgmentsUpdatedDt: '-acknowledgments__updated_dt',
    AcknowledgmentsUuid: '-acknowledgments__uuid',
    AffectsAffectedness: '-affects__affectedness',
    AffectsCreatedDt: '-affects__created_dt',
    AffectsImpact: '-affects__impact',
    AffectsPsComponent: '-affects__ps_component',
    AffectsPsModule: '-affects__ps_module',
    AffectsResolution: '-affects__resolution',
    AffectsTrackersCreatedDt: '-affects__trackers__created_dt',
    AffectsTrackersErrataAdvisoryName: '-affects__trackers__errata__advisory_name',
    AffectsTrackersErrataEtId: '-affects__trackers__errata__et_id',
    AffectsTrackersErrataShippedDt: '-affects__trackers__errata__shipped_dt',
    AffectsTrackersExternalSystemId: '-affects__trackers__external_system_id',
    AffectsTrackersPsUpdateStream: '-affects__trackers__ps_update_stream',
    AffectsTrackersResolution: '-affects__trackers__resolution',
    AffectsTrackersStatus: '-affects__trackers__status',
    AffectsTrackersType: '-affects__trackers__type',
    AffectsTrackersUpdatedDt: '-affects__trackers__updated_dt',
    AffectsTrackersUuid: '-affects__trackers__uuid',
    AffectsUpdatedDt: '-affects__updated_dt',
    AffectsUuid: '-affects__uuid',
    BzId: '-bz_id',
    CommentZero: '-comment_zero',
    Components: '-components',
    CreatedDt: '-created_dt',
    CveDescription: '-cve_description',
    CveId: '-cve_id',
    CvssScoresComment: '-cvss_scores__comment',
    CvssScoresCreatedDt: '-cvss_scores__created_dt',
    CvssScoresIssuer: '-cvss_scores__issuer',
    CvssScoresScore: '-cvss_scores__score',
    CvssScoresUpdatedDt: '-cvss_scores__updated_dt',
    CvssScoresUuid: '-cvss_scores__uuid',
    CvssScoresVector: '-cvss_scores__vector',
    CweId: '-cwe_id',
    Embargoed: '-embargoed',
    Impact: '-impact',
    MajorIncidentStartDt: '-major_incident_start_dt',
    MajorIncidentState: '-major_incident_state',
    NistCvssValidation: '-nist_cvss_validation',
    Owner: '-owner',
    ReferencesCreatedDt: '-references__created_dt',
    ReferencesDescription: '-references__description',
    ReferencesType: '-references__type',
    ReferencesUpdatedDt: '-references__updated_dt',
    ReferencesUrl: '-references__url',
    ReferencesUuid: '-references__uuid',
    ReportedDt: '-reported_dt',
    RequiresCveDescription: '-requires_cve_description',
    Source: '-source',
    Statement: '-statement',
    TeamId: '-team_id',
    Title: '-title',
    UnembargoDt: '-unembargo_dt',
    UpdatedDt: '-updated_dt',
    Uuid: '-uuid',
    WorkflowState: '-workflow_state',
    AcknowledgmentsAffiliation: 'acknowledgments__affiliation',
    AcknowledgmentsCreatedDt: 'acknowledgments__created_dt',
    AcknowledgmentsFromUpstream: 'acknowledgments__from_upstream',
    AcknowledgmentsName: 'acknowledgments__name',
    AcknowledgmentsUpdatedDt: 'acknowledgments__updated_dt',
    AcknowledgmentsUuid: 'acknowledgments__uuid',
    AffectsAffectedness: 'affects__affectedness',
    AffectsCreatedDt: 'affects__created_dt',
    AffectsImpact: 'affects__impact',
    AffectsPsComponent: 'affects__ps_component',
    AffectsPsModule: 'affects__ps_module',
    AffectsResolution: 'affects__resolution',
    AffectsTrackersCreatedDt: 'affects__trackers__created_dt',
    AffectsTrackersErrataAdvisoryName: 'affects__trackers__errata__advisory_name',
    AffectsTrackersErrataEtId: 'affects__trackers__errata__et_id',
    AffectsTrackersErrataShippedDt: 'affects__trackers__errata__shipped_dt',
    AffectsTrackersExternalSystemId: 'affects__trackers__external_system_id',
    AffectsTrackersPsUpdateStream: 'affects__trackers__ps_update_stream',
    AffectsTrackersResolution: 'affects__trackers__resolution',
    AffectsTrackersStatus: 'affects__trackers__status',
    AffectsTrackersType: 'affects__trackers__type',
    AffectsTrackersUpdatedDt: 'affects__trackers__updated_dt',
    AffectsTrackersUuid: 'affects__trackers__uuid',
    AffectsUpdatedDt: 'affects__updated_dt',
    AffectsUuid: 'affects__uuid',
    BzId: 'bz_id',
    CommentZero: 'comment_zero',
    Components: 'components',
    CreatedDt: 'created_dt',
    CveDescription: 'cve_description',
    CveId: 'cve_id',
    CvssScoresComment: 'cvss_scores__comment',
    CvssScoresCreatedDt: 'cvss_scores__created_dt',
    CvssScoresIssuer: 'cvss_scores__issuer',
    CvssScoresScore: 'cvss_scores__score',
    CvssScoresUpdatedDt: 'cvss_scores__updated_dt',
    CvssScoresUuid: 'cvss_scores__uuid',
    CvssScoresVector: 'cvss_scores__vector',
    CweId: 'cwe_id',
    Embargoed: 'embargoed',
    Impact: 'impact',
    MajorIncidentStartDt: 'major_incident_start_dt',
    MajorIncidentState: 'major_incident_state',
    NistCvssValidation: 'nist_cvss_validation',
    Owner: 'owner',
    ReferencesCreatedDt: 'references__created_dt',
    ReferencesDescription: 'references__description',
    ReferencesType: 'references__type',
    ReferencesUpdatedDt: 'references__updated_dt',
    ReferencesUrl: 'references__url',
    ReferencesUuid: 'references__uuid',
    ReportedDt: 'reported_dt',
    RequiresCveDescription: 'requires_cve_description',
    Source: 'source',
    Statement: 'statement',
    TeamId: 'team_id',
    Title: 'title',
    UnembargoDt: 'unembargo_dt',
    UpdatedDt: 'updated_dt',
    Uuid: 'uuid',
    WorkflowState: 'workflow_state'
} as const;
export type OsidbApiV1FlawsListOrderEnum = typeof OsidbApiV1FlawsListOrderEnum[keyof typeof OsidbApiV1FlawsListOrderEnum];

export const OsidbApiV1FlawsListReferencesTypeEnum = {
    Article: 'ARTICLE',
    External: 'EXTERNAL',
    Source: 'SOURCE',
    Upstream: 'UPSTREAM'
} as const;
export type OsidbApiV1FlawsListReferencesTypeEnum = typeof OsidbApiV1FlawsListReferencesTypeEnum[keyof typeof OsidbApiV1FlawsListReferencesTypeEnum];

export const OsidbApiV1FlawsListRequiresCveDescriptionEnum = {
    Empty: '',
    Approved: 'APPROVED',
    Rejected: 'REJECTED',
    Requested: 'REQUESTED'
} as const;
export type OsidbApiV1FlawsListRequiresCveDescriptionEnum = typeof OsidbApiV1FlawsListRequiresCveDescriptionEnum[keyof typeof OsidbApiV1FlawsListRequiresCveDescriptionEnum];

export const OsidbApiV1FlawsListSourceEnum = {
    Empty: '',
    Adobe: 'ADOBE',
    Apple: 'APPLE',
    Asf: 'ASF',
    Bind: 'BIND',
    Bk: 'BK',
    Bugtraq: 'BUGTRAQ',
    Bugzilla: 'BUGZILLA',
    Cert: 'CERT',
    Certifi: 'CERTIFI',
    Corelabs: 'CORELABS',
    Customer: 'CUSTOMER',
    Cve: 'CVE',
    Cveorg: 'CVEORG',
    Dailydave: 'DAILYDAVE',
    Debian: 'DEBIAN',
    Distros: 'DISTROS',
    Fedora: 'FEDORA',
    Fetchmail: 'FETCHMAIL',
    Freedesktop: 'FREEDESKTOP',
    Freeradius: 'FREERADIUS',
    Frsirt: 'FRSIRT',
    Fulldisclosure: 'FULLDISCLOSURE',
    Gaim: 'GAIM',
    Gentoo: 'GENTOO',
    Gentoobz: 'GENTOOBZ',
    Git: 'GIT',
    Gnome: 'GNOME',
    Gnupg: 'GNUPG',
    Google: 'GOOGLE',
    Hp: 'HP',
    HwVendor: 'HW_VENDOR',
    Ibm: 'IBM',
    Idefense: 'IDEFENSE',
    Internet: 'INTERNET',
    Isc: 'ISC',
    Isec: 'ISEC',
    It: 'IT',
    Jboss: 'JBOSS',
    Jpcert: 'JPCERT',
    Kernelbugzilla: 'KERNELBUGZILLA',
    Kernelsec: 'KERNELSEC',
    Lkml: 'LKML',
    Lwn: 'LWN',
    Macromedia: 'MACROMEDIA',
    Mageia: 'MAGEIA',
    Mailinglist: 'MAILINGLIST',
    Milw0Rm: 'MILW0RM',
    Mit: 'MIT',
    Mitre: 'MITRE',
    Mozilla: 'MOZILLA',
    Muttdev: 'MUTTDEV',
    Netdev: 'NETDEV',
    Niscc: 'NISCC',
    Nvd: 'NVD',
    Ocert: 'OCERT',
    Openoffice: 'OPENOFFICE',
    Openssl: 'OPENSSL',
    Opensuse: 'OPENSUSE',
    Oracle: 'ORACLE',
    Oss: 'OSS',
    Osssecurity: 'OSSSECURITY',
    Osv: 'OSV',
    Php: 'PHP',
    Pidgin: 'PIDGIN',
    Postgresql: 'POSTGRESQL',
    Press: 'PRESS',
    Real: 'REAL',
    Redhat: 'REDHAT',
    Researcher: 'RESEARCHER',
    Rt: 'RT',
    Samba: 'SAMBA',
    Secalert: 'SECALERT',
    Secunia: 'SECUNIA',
    Securityfocus: 'SECURITYFOCUS',
    Sko: 'SKO',
    Squid: 'SQUID',
    Squirrelmail: 'SQUIRRELMAIL',
    Sun: 'SUN',
    Sunsolve: 'SUNSOLVE',
    Suse: 'SUSE',
    Twitter: 'TWITTER',
    Ubuntu: 'UBUNTU',
    Upstream: 'UPSTREAM',
    Vendorsec: 'VENDORSEC',
    Vulnwatch: 'VULNWATCH',
    Wireshark: 'WIRESHARK',
    Xchat: 'XCHAT',
    Xen: 'XEN',
    Xpdf: 'XPDF'
} as const;
export type OsidbApiV1FlawsListSourceEnum = typeof OsidbApiV1FlawsListSourceEnum[keyof typeof OsidbApiV1FlawsListSourceEnum];

export const OsidbApiV1FlawsListWorkflowStateEnum = {
    Empty: '',
    Done: 'DONE',
    New: 'NEW',
    PreSecondaryAssessment: 'PRE_SECONDARY_ASSESSMENT',
    Rejected: 'REJECTED',
    SecondaryAssessment: 'SECONDARY_ASSESSMENT',
    Triage: 'TRIAGE'
} as const;
export type OsidbApiV1FlawsListWorkflowStateEnum = typeof OsidbApiV1FlawsListWorkflowStateEnum[keyof typeof OsidbApiV1FlawsListWorkflowStateEnum];

export const OsidbApiV1FlawsReferencesListTypeEnum = {
    Article: 'ARTICLE',
    External: 'EXTERNAL',
    Source: 'SOURCE',
    Upstream: 'UPSTREAM'
} as const;
export type OsidbApiV1FlawsReferencesListTypeEnum = typeof OsidbApiV1FlawsReferencesListTypeEnum[keyof typeof OsidbApiV1FlawsReferencesListTypeEnum];

export const OsidbApiV1SchemaRetrieveFormatEnum = {
    Json: 'json',
    Yaml: 'yaml'
} as const;
export type OsidbApiV1SchemaRetrieveFormatEnum = typeof OsidbApiV1SchemaRetrieveFormatEnum[keyof typeof OsidbApiV1SchemaRetrieveFormatEnum];

export const OsidbApiV1SchemaRetrieveLangEnum = {
    Af: 'af',
    Ar: 'ar',
    ArDz: 'ar-dz',
    Ast: 'ast',
    Az: 'az',
    Be: 'be',
    Bg: 'bg',
    Bn: 'bn',
    Br: 'br',
    Bs: 'bs',
    Ca: 'ca',
    Ckb: 'ckb',
    Cs: 'cs',
    Cy: 'cy',
    Da: 'da',
    De: 'de',
    Dsb: 'dsb',
    El: 'el',
    En: 'en',
    EnAu: 'en-au',
    EnGb: 'en-gb',
    Eo: 'eo',
    Es: 'es',
    EsAr: 'es-ar',
    EsCo: 'es-co',
    EsMx: 'es-mx',
    EsNi: 'es-ni',
    EsVe: 'es-ve',
    Et: 'et',
    Eu: 'eu',
    Fa: 'fa',
    Fi: 'fi',
    Fr: 'fr',
    Fy: 'fy',
    Ga: 'ga',
    Gd: 'gd',
    Gl: 'gl',
    He: 'he',
    Hi: 'hi',
    Hr: 'hr',
    Hsb: 'hsb',
    Hu: 'hu',
    Hy: 'hy',
    Ia: 'ia',
    Id: 'id',
    Ig: 'ig',
    Io: 'io',
    Is: 'is',
    It: 'it',
    Ja: 'ja',
    Ka: 'ka',
    Kab: 'kab',
    Kk: 'kk',
    Km: 'km',
    Kn: 'kn',
    Ko: 'ko',
    Ky: 'ky',
    Lb: 'lb',
    Lt: 'lt',
    Lv: 'lv',
    Mk: 'mk',
    Ml: 'ml',
    Mn: 'mn',
    Mr: 'mr',
    Ms: 'ms',
    My: 'my',
    Nb: 'nb',
    Ne: 'ne',
    Nl: 'nl',
    Nn: 'nn',
    Os: 'os',
    Pa: 'pa',
    Pl: 'pl',
    Pt: 'pt',
    PtBr: 'pt-br',
    Ro: 'ro',
    Ru: 'ru',
    Sk: 'sk',
    Sl: 'sl',
    Sq: 'sq',
    Sr: 'sr',
    SrLatn: 'sr-latn',
    Sv: 'sv',
    Sw: 'sw',
    Ta: 'ta',
    Te: 'te',
    Tg: 'tg',
    Th: 'th',
    Tk: 'tk',
    Tr: 'tr',
    Tt: 'tt',
    Udm: 'udm',
    Uk: 'uk',
    Ur: 'ur',
    Uz: 'uz',
    Vi: 'vi',
    ZhHans: 'zh-hans',
    ZhHant: 'zh-hant'
} as const;
export type OsidbApiV1SchemaRetrieveLangEnum = typeof OsidbApiV1SchemaRetrieveLangEnum[keyof typeof OsidbApiV1SchemaRetrieveLangEnum];

export const OsidbApiV1TrackersListAffectsAffectednessEnum = {
    Empty: '',
    Affected: 'AFFECTED',
    New: 'NEW',
    Notaffected: 'NOTAFFECTED'
} as const;
export type OsidbApiV1TrackersListAffectsAffectednessEnum = typeof OsidbApiV1TrackersListAffectsAffectednessEnum[keyof typeof OsidbApiV1TrackersListAffectsAffectednessEnum];

export const OsidbApiV1TrackersListAffectsFlawImpactEnum = {
    Empty: '',
    Critical: 'CRITICAL',
    Important: 'IMPORTANT',
    Low: 'LOW',
    Moderate: 'MODERATE'
} as const;
export type OsidbApiV1TrackersListAffectsFlawImpactEnum = typeof OsidbApiV1TrackersListAffectsFlawImpactEnum[keyof typeof OsidbApiV1TrackersListAffectsFlawImpactEnum];

export const OsidbApiV1TrackersListAffectsFlawSourceEnum = {
    Empty: '',
    Adobe: 'ADOBE',
    Apple: 'APPLE',
    Asf: 'ASF',
    Bind: 'BIND',
    Bk: 'BK',
    Bugtraq: 'BUGTRAQ',
    Bugzilla: 'BUGZILLA',
    Cert: 'CERT',
    Certifi: 'CERTIFI',
    Corelabs: 'CORELABS',
    Customer: 'CUSTOMER',
    Cve: 'CVE',
    Cveorg: 'CVEORG',
    Dailydave: 'DAILYDAVE',
    Debian: 'DEBIAN',
    Distros: 'DISTROS',
    Fedora: 'FEDORA',
    Fetchmail: 'FETCHMAIL',
    Freedesktop: 'FREEDESKTOP',
    Freeradius: 'FREERADIUS',
    Frsirt: 'FRSIRT',
    Fulldisclosure: 'FULLDISCLOSURE',
    Gaim: 'GAIM',
    Gentoo: 'GENTOO',
    Gentoobz: 'GENTOOBZ',
    Git: 'GIT',
    Gnome: 'GNOME',
    Gnupg: 'GNUPG',
    Google: 'GOOGLE',
    Hp: 'HP',
    HwVendor: 'HW_VENDOR',
    Ibm: 'IBM',
    Idefense: 'IDEFENSE',
    Internet: 'INTERNET',
    Isc: 'ISC',
    Isec: 'ISEC',
    It: 'IT',
    Jboss: 'JBOSS',
    Jpcert: 'JPCERT',
    Kernelbugzilla: 'KERNELBUGZILLA',
    Kernelsec: 'KERNELSEC',
    Lkml: 'LKML',
    Lwn: 'LWN',
    Macromedia: 'MACROMEDIA',
    Mageia: 'MAGEIA',
    Mailinglist: 'MAILINGLIST',
    Milw0Rm: 'MILW0RM',
    Mit: 'MIT',
    Mitre: 'MITRE',
    Mozilla: 'MOZILLA',
    Muttdev: 'MUTTDEV',
    Netdev: 'NETDEV',
    Niscc: 'NISCC',
    Nvd: 'NVD',
    Ocert: 'OCERT',
    Openoffice: 'OPENOFFICE',
    Openssl: 'OPENSSL',
    Opensuse: 'OPENSUSE',
    Oracle: 'ORACLE',
    Oss: 'OSS',
    Osssecurity: 'OSSSECURITY',
    Osv: 'OSV',
    Php: 'PHP',
    Pidgin: 'PIDGIN',
    Postgresql: 'POSTGRESQL',
    Press: 'PRESS',
    Real: 'REAL',
    Redhat: 'REDHAT',
    Researcher: 'RESEARCHER',
    Rt: 'RT',
    Samba: 'SAMBA',
    Secalert: 'SECALERT',
    Secunia: 'SECUNIA',
    Securityfocus: 'SECURITYFOCUS',
    Sko: 'SKO',
    Squid: 'SQUID',
    Squirrelmail: 'SQUIRRELMAIL',
    Sun: 'SUN',
    Sunsolve: 'SUNSOLVE',
    Suse: 'SUSE',
    Twitter: 'TWITTER',
    Ubuntu: 'UBUNTU',
    Upstream: 'UPSTREAM',
    Vendorsec: 'VENDORSEC',
    Vulnwatch: 'VULNWATCH',
    Wireshark: 'WIRESHARK',
    Xchat: 'XCHAT',
    Xen: 'XEN',
    Xpdf: 'XPDF'
} as const;
export type OsidbApiV1TrackersListAffectsFlawSourceEnum = typeof OsidbApiV1TrackersListAffectsFlawSourceEnum[keyof typeof OsidbApiV1TrackersListAffectsFlawSourceEnum];

export const OsidbApiV1TrackersListAffectsImpactEnum = {
    Empty: '',
    Critical: 'CRITICAL',
    Important: 'IMPORTANT',
    Low: 'LOW',
    Moderate: 'MODERATE'
} as const;
export type OsidbApiV1TrackersListAffectsImpactEnum = typeof OsidbApiV1TrackersListAffectsImpactEnum[keyof typeof OsidbApiV1TrackersListAffectsImpactEnum];

export const OsidbApiV1TrackersListAffectsResolutionEnum = {
    Empty: '',
    Defer: 'DEFER',
    Delegated: 'DELEGATED',
    Fix: 'FIX',
    Ooss: 'OOSS',
    Wontfix: 'WONTFIX',
    Wontreport: 'WONTREPORT'
} as const;
export type OsidbApiV1TrackersListAffectsResolutionEnum = typeof OsidbApiV1TrackersListAffectsResolutionEnum[keyof typeof OsidbApiV1TrackersListAffectsResolutionEnum];

export const OsidbApiV1TrackersListOrderEnum = {
    AffectsAffectedness: '-affects__affectedness',
    AffectsCreatedDt: '-affects__created_dt',
    AffectsEmbargoed: '-affects__embargoed',
    AffectsFlawComponents: '-affects__flaw__components',
    AffectsFlawCreatedDt: '-affects__flaw__created_dt',
    AffectsFlawCveId: '-affects__flaw__cve_id',
    AffectsFlawCweId: '-affects__flaw__cwe_id',
    AffectsFlawEmbargoed: '-affects__flaw__embargoed',
    AffectsFlawImpact: '-affects__flaw__impact',
    AffectsFlawReportedDt: '-affects__flaw__reported_dt',
    AffectsFlawSource: '-affects__flaw__source',
    AffectsFlawUnembargoDt: '-affects__flaw__unembargo_dt',
    AffectsFlawUpdatedDt: '-affects__flaw__updated_dt',
    AffectsFlawUuid: '-affects__flaw__uuid',
    AffectsImpact: '-affects__impact',
    AffectsPsComponent: '-affects__ps_component',
    AffectsPsModule: '-affects__ps_module',
    AffectsResolution: '-affects__resolution',
    AffectsUpdatedDt: '-affects__updated_dt',
    AffectsUuid: '-affects__uuid',
    CreatedDt: '-created_dt',
    CveId: '-cve_id',
    Embargoed: '-embargoed',
    ExternalSystemId: '-external_system_id',
    PsUpdateStream: '-ps_update_stream',
    Resolution: '-resolution',
    Status: '-status',
    Type: '-type',
    UpdatedDt: '-updated_dt',
    Uuid: '-uuid',
    AffectsAffectedness: 'affects__affectedness',
    AffectsCreatedDt: 'affects__created_dt',
    AffectsEmbargoed: 'affects__embargoed',
    AffectsFlawComponents: 'affects__flaw__components',
    AffectsFlawCreatedDt: 'affects__flaw__created_dt',
    AffectsFlawCveId: 'affects__flaw__cve_id',
    AffectsFlawCweId: 'affects__flaw__cwe_id',
    AffectsFlawEmbargoed: 'affects__flaw__embargoed',
    AffectsFlawImpact: 'affects__flaw__impact',
    AffectsFlawReportedDt: 'affects__flaw__reported_dt',
    AffectsFlawSource: 'affects__flaw__source',
    AffectsFlawUnembargoDt: 'affects__flaw__unembargo_dt',
    AffectsFlawUpdatedDt: 'affects__flaw__updated_dt',
    AffectsFlawUuid: 'affects__flaw__uuid',
    AffectsImpact: 'affects__impact',
    AffectsPsComponent: 'affects__ps_component',
    AffectsPsModule: 'affects__ps_module',
    AffectsResolution: 'affects__resolution',
    AffectsUpdatedDt: 'affects__updated_dt',
    AffectsUuid: 'affects__uuid',
    CreatedDt: 'created_dt',
    CveId: 'cve_id',
    Embargoed: 'embargoed',
    ExternalSystemId: 'external_system_id',
    PsUpdateStream: 'ps_update_stream',
    Resolution: 'resolution',
    Status: 'status',
    Type: 'type',
    UpdatedDt: 'updated_dt',
    Uuid: 'uuid'
} as const;
export type OsidbApiV1TrackersListOrderEnum = typeof OsidbApiV1TrackersListOrderEnum[keyof typeof OsidbApiV1TrackersListOrderEnum];

export const OsidbApiV1TrackersListTypeEnum = {
    Bugzilla: 'BUGZILLA',
    Jira: 'JIRA'
} as const;
export type OsidbApiV1TrackersListTypeEnum = typeof OsidbApiV1TrackersListTypeEnum[keyof typeof OsidbApiV1TrackersListTypeEnum];

export const OsidbApiV2betaAffectsCvssScoresListIssuerEnum = {
    Cisa: 'CISA',
    Cveorg: 'CVEORG',
    Nist: 'NIST',
    Osv: 'OSV',
    Rh: 'RH'
} as const;
export type OsidbApiV2betaAffectsCvssScoresListIssuerEnum = typeof OsidbApiV2betaAffectsCvssScoresListIssuerEnum[keyof typeof OsidbApiV2betaAffectsCvssScoresListIssuerEnum];

export const OsidbApiV2betaFlawsCvssScoresListIssuerEnum = {
    Cisa: 'CISA',
    Cveorg: 'CVEORG',
    Nist: 'NIST',
    Osv: 'OSV',
    Rh: 'RH'
} as const;
export type OsidbApiV2betaFlawsCvssScoresListIssuerEnum = typeof OsidbApiV2betaFlawsCvssScoresListIssuerEnum[keyof typeof OsidbApiV2betaFlawsCvssScoresListIssuerEnum];
