/* tslint:disable */
/* eslint-disable */
/**
 * OSIDB API
 * REST API autogenerated docs for the OSIDB and its components
 *
 * The version of the OpenAPI document: 4.12.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type {
  FlawUUIDListRequest,
  TrackersApiV1FileCreate200Response,
} from '../models';

/**
* Given a list of flaws, generates a list of suggested trackers to file.
* @Path /trackers/api/v1/file
* @Method POST
*/
export type trackersApiV1FileCreate = FlawUUIDListRequest;

