/* tslint:disable */
/* eslint-disable */
/**
 * OSIDB API
 * REST API autogenerated docs for the OSIDB and its components
 *
 * The version of the OpenAPI document: 4.12.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type {
  AuthTokenCreate200ResponseAllOf,
} from '../models';

/**
* workflow adjustion API endpoint  adjust workflow classification of flaw identified by UUID or CVE and return its workflow:state classification (new if changed and old otherwise)  adjust operation is idempotent so when the classification is already adjusted running it results in no operation
* @Path /workflows/api/v1/workflows/{id}/adjust
* @Method POST
*/
export type workflowsApiV1WorkflowsAdjustCreate = {
}
/**
* workflow info API endpoint
* @Path /workflows/api/v1/workflows
* @Method GET
*/
/**
* workflow classification API endpoint  for flaw identified by UUID or CVE returns its workflow:state classification  params:      verbose - return also workflows with flaw classification               which represents the reasoning of the result
* @Path /workflows/api/v1/workflows/{id}
* @Method GET
*/
export type workflowsApiV1WorkflowsRetrieve2 = {
    verbose: boolean;
}
/**
* unauthenticated health check API endpoint
* @Path /workflows/healthy
* @Method GET
*/
/**
* index API endpoint listing available API endpoints
* @Path /workflows/
* @Method GET
*/

