<script setup lang="ts">
import { computed, type Ref } from 'vue';

import AegisActions from '@/components/Aegis/AegisActions.vue';

import { useAegisSuggestion } from '@/composables/aegis/useAegisSuggestion';
import type { AegisSuggestionContextRefs } from '@/composables/aegis/useAegisSuggestionContext';
import { useAegisFieldFeedback } from '@/composables/aegis/useAegisFieldFeedback';
import { useAegisMetadataTracking } from '@/composables/aegis/useAegisMetadataTracking';

const props = withDefaults(defineProps<{
  aegisContext?: AegisSuggestionContextRefs | null;
}>(), {
  aegisContext: null,
});

const modelValue = defineModel<null | string[] | undefined>('modelValue');

const {
  allSuggestions,
  canShowFeedback,
  canSuggest,
  details: componentsSuggestionDetails,
  hasAppliedSuggestion,
  isFetchingSuggestion,
  revert: revertComponents,
  selectedSuggestionIndex,
  selectSuggestion,
  sendFeedback,
  suggestComponents,
} = useAegisSuggestion(
  props.aegisContext as AegisSuggestionContextRefs,
  modelValue as Ref<null | string[] | undefined>,
  'components',
);

const { getAIBotTooltip } = useAegisMetadataTracking();

const {
  canShowFeedbackExtended,
  handleFieldFeedback: handleComponentsFeedback,
  isFieldAIBot: isComponentsAIBot,
} = useAegisFieldFeedback(
  'components',
  modelValue,
  canShowFeedback,
  hasAppliedSuggestion,
  sendFeedback,
);

defineExpose({
  isFetchingSuggestion,
});

const suggestionTooltip = computed(() => {
  if (hasAppliedSuggestion.value && componentsSuggestionDetails.value?.explanation) {
    const title = isComponentsAIBot.value ? 'Generated by Aegis-AI-Bot' : 'Generated by Aegis-AI';
    return `${title}\n\n${componentsSuggestionDetails.value.explanation}`;
  }
  const aiBotTooltip = getAIBotTooltip('components');
  if (aiBotTooltip && aiBotTooltip !== 'Generated by Aegis-AI-Bot') {
    return aiBotTooltip.replace(/<br><br>/g, '\n\n');
  }
  return '';
});
</script>

<template>
  <AegisActions
    :canSuggest="canSuggest"
    :hasAppliedSuggestion="hasAppliedSuggestion"
    :hasMultipleSuggestions="false"
    :isFetchingSuggestion="isFetchingSuggestion"
    :canShowFeedback="canShowFeedbackExtended"
    :isFieldAIBot="isComponentsAIBot"
    :suggestions="allSuggestions as string[]"
    :selectedIndex="selectedSuggestionIndex"
    :tooltipText="suggestionTooltip"
    @suggest="suggestComponents"
    @selectSuggestion="selectSuggestion"
    @revert="revertComponents"
    @feedback="handleComponentsFeedback"
  >
    <template #suggestion-item="{ suggestions, selectedIndex, selectSuggestion: selectSuggestionFn }">
      <li v-for="(suggestionItem, index) in suggestions" :key="index">
        <button
          class="dropdown-item"
          :class="{ 'active': index === selectedIndex }"
          type="button"
          @click="selectSuggestionFn(index)"
        >
          <div class="flex-grow-1 d-flex flex-column" style="gap: 0.15rem;">
            <span class="fw-bold fs-7">{{ suggestionItem }}</span>
          </div>
        </button>
      </li>
    </template>
  </AegisActions>
</template>

<style scoped lang="scss">
.icon-link {
  color: gray;
  text-decoration: none;

  &:hover {
    color: #0d6efd;
  }
}
</style>
