<script setup lang="ts">
import { computed, ref, watch } from 'vue';

import AegisActions from '@/components/Aegis/AegisActions.vue';

import { useAegisSuggestion } from '@/composables/aegis/useAegisSuggestion';
import type { AegisSuggestionContextRefs } from '@/composables/aegis/useAegisSuggestionContext';
import { useCvssScores } from '@/composables/useCvssScores';
import { useAegisFieldFeedback } from '@/composables/aegis/useAegisFieldFeedback';
import { useAegisMetadataTracking } from '@/composables/aegis/useAegisMetadataTracking';

const props = withDefaults(defineProps<{
  aegisContext?: AegisSuggestionContextRefs | null;
}>(), {
  aegisContext: null,
});

const emit = defineEmits<{ 'update:cvssVector': [vector: null | string] }>();
const emitUpdateCvssVector = (vector: null | string) => emit('update:cvssVector', vector);

// Initialize with the actual current CVSS vector
const { cvssVector } = useCvssScores();
const suggestedCvssVector = ref<null | string>(cvssVector.value);

// Keep in sync with actual CVSS changes
watch(cvssVector, (newVector) => {
  suggestedCvssVector.value = newVector;
});

watch(suggestedCvssVector, emitUpdateCvssVector);

const {
  allSuggestions,
  canShowFeedback,
  canSuggest,
  currentSuggestion: _currentCVSS,
  details: suggestionDetails,
  hasAppliedSuggestion,
  hasMultipleSuggestions,
  isFetchingSuggestion,
  revert: revertCvss,
  selectedSuggestionIndex,
  selectSuggestion,
  sendFeedback,
  suggestCvss,
} = useAegisSuggestion(props.aegisContext as AegisSuggestionContextRefs, suggestedCvssVector, '_cvss3_vector');

const { getAIBotTooltip } = useAegisMetadataTracking();

const {
  canShowFeedbackExtended,
  handleFieldFeedback: handleCvssFeedback,
  isFieldAIBot: isCvssAIBot,
} = useAegisFieldFeedback(
  '_cvss3_vector',
  cvssVector,
  canShowFeedback,
  hasAppliedSuggestion,
  sendFeedback,
);

defineExpose({
  isFetchingSuggestion,
});

const suggestionTooltip = computed(() => {
  // If field is AI-Bot from history, use the tooltip from metadata
  if (isCvssAIBot.value && !hasAppliedSuggestion.value) {
    const tooltip = getAIBotTooltip('_cvss3_vector');
    // Convert <br> to \n for consistency with other tooltips
    return tooltip.replace(/<br><br>/g, '\n\n');
  }

  // Otherwise use the suggestion details if available
  if (!hasAppliedSuggestion.value || !suggestionDetails.value) return 'Generated by Aegis-AI';
  const { explanation } = suggestionDetails.value;
  const title = isCvssAIBot.value ? 'Generated by Aegis-AI-Bot' : 'Generated by Aegis-AI';
  if (explanation) {
    return `${title}\n\n${explanation}`;
  }
  return title;
});
</script>

<template>
  <AegisActions
    :canSuggest="canSuggest"
    :hasAppliedSuggestion="hasAppliedSuggestion"
    :hasMultipleSuggestions="hasMultipleSuggestions"
    :isFetchingSuggestion="isFetchingSuggestion"
    :canShowFeedback="canShowFeedbackExtended"
    :isFieldAIBot="isCvssAIBot"
    :suggestions="allSuggestions"
    :selectedIndex="selectedSuggestionIndex"
    :tooltipText="suggestionTooltip"
    @suggest="suggestCvss"
    @selectSuggestion="selectSuggestion"
    @revert="revertCvss"
    @feedback="handleCvssFeedback"
  >
    <template #suggestion-item="{ suggestions, selectedIndex, selectSuggestion: selectSuggestionFn }">
      <li v-for="(suggestion, index) in suggestions" :key="index">
        <button
          class="dropdown-item"
          :class="{ 'active': index === selectedIndex }"
          type="button"
          @click="selectSuggestionFn(index)"
        >
          <div class="flex-grow-1 d-flex flex-column" style="gap: 0.15rem;">
            <span class="fw-bold fs-7">{{ suggestion }}</span>

          </div>
        </button>
      </li>
    </template>
  </AegisActions>
</template>

<style scoped lang="scss">
.icon-link {
  color: gray;
  text-decoration: none;

  &:hover {
    color: #0d6efd;
  }
}
</style>
