<script setup lang="ts">
import { computed } from 'vue';

import AegisActions from '@/components/Aegis/AegisActions.vue';

import type { UseAegisSuggestDescriptionReturn } from '@/composables/aegis/useAegisSuggestDescription';
import { useAegisFieldFeedback } from '@/composables/aegis/useAegisFieldFeedback';
import { useAegisMetadataTracking } from '@/composables/aegis/useAegisMetadataTracking';

const props = defineProps<{
  composable: UseAegisSuggestDescriptionReturn;
  descriptionValue?: null | string;
}>();

const {
  canShowDescriptionFeedback,
  canSuggest,
  details: suggestionDetails,
  hasAppliedDescriptionSuggestion,
  isSuggesting,
  revertDescription,
  sendDescriptionFeedback,
  suggestDescription,
} = props.composable;

defineExpose({
  isSuggesting,
});

const { getAIBotTooltip } = useAegisMetadataTracking();

const {
  canShowFeedbackExtended: canShowDescriptionFeedbackExtended,
  handleFieldFeedback: handleDescriptionFeedback,
  isFieldAIBot: isDescriptionAIBot,
} = useAegisFieldFeedback(
  'cve_description',
  computed(() => props.descriptionValue),
  canShowDescriptionFeedback,
  hasAppliedDescriptionSuggestion,
  sendDescriptionFeedback,
);

const suggestionTooltip = computed(() => {
  // If there's a current applied suggestion with details, use that
  if (hasAppliedDescriptionSuggestion.value && suggestionDetails.value?.explanation) {
    const title = isDescriptionAIBot.value ? 'Generated by Aegis-AI-Bot' : 'Generated by Aegis-AI';
    return `${title}\n\n${suggestionDetails.value.explanation}`;
  }

  // Otherwise try to get AI-Bot tooltip content
  const aiBotTooltip = getAIBotTooltip('cve_description');
  if (aiBotTooltip && aiBotTooltip !== 'Generated by Aegis-AI-Bot') {
    return aiBotTooltip.replace(/<br><br>/g, '\n\n');
  }

  return '';
});
</script>

<template>
  <AegisActions
    :canSuggest="canSuggest"
    :hasAppliedSuggestion="hasAppliedDescriptionSuggestion"
    :hasMultipleSuggestions="false"
    :isFetchingSuggestion="isSuggesting"
    :canShowFeedback="canShowDescriptionFeedbackExtended"
    :isFieldAIBot="isDescriptionAIBot"
    :suggestions="[]"
    :selectedIndex="0"
    :tooltipText="suggestionTooltip"
    @suggest="suggestDescription"
    @revert="revertDescription"
    @feedback="handleDescriptionFeedback"
  />
</template>
