<script setup lang="ts">
import { computed } from 'vue';

import AegisActions from '@/components/Aegis/AegisActions.vue';

import type { UseAegisSuggestDescriptionReturn } from '@/composables/aegis/useAegisSuggestDescription';
import { useAegisFieldFeedback } from '@/composables/aegis/useAegisFieldFeedback';
import { useAegisMetadataTracking } from '@/composables/aegis/useAegisMetadataTracking';

import { osimRuntime } from '@/stores/osimRuntime';

const props = defineProps<{
  composable: UseAegisSuggestDescriptionReturn;
  titleValue?: null | string;
}>();

const {
  canShowTitleFeedback,
  canSuggest,
  details: suggestionDetails,
  hasAppliedTitleSuggestion,
  isSuggesting,
  revertTitle,
  sendTitleFeedback,
  suggestDescription,
} = props.composable;

defineExpose({
  isSuggesting,
});

const { getAIBotTooltip } = useAegisMetadataTracking();

const {
  canShowFeedbackExtended: canShowTitleFeedbackExtended,
  handleFieldFeedback: handleTitleFeedback,
  isFieldAIBot: isTitleAIBot,
} = useAegisFieldFeedback(
  'title',
  computed(() => props.titleValue),
  canShowTitleFeedback,
  hasAppliedTitleSuggestion,
  sendTitleFeedback,
);

const suggestionTooltip = computed(() => {
  // If field is AI-Bot from history, use the tooltip from metadata
  if (isTitleAIBot.value && !hasAppliedTitleSuggestion.value) {
    const tooltip = getAIBotTooltip('title');
    // Convert <br> to \n for consistency with other tooltips
    return tooltip.replace(/<br><br>/g, '\n\n');
  }

  // Otherwise use the suggestion details if available
  if (!hasAppliedTitleSuggestion.value || !suggestionDetails.value) return 'Generated by Aegis-AI';
  const { explanation } = suggestionDetails.value;
  const title = isTitleAIBot.value ? 'Generated by Aegis-AI-Bot' : 'Generated by Aegis-AI';
  if (explanation) {
    return `${title}\n\n${explanation}`;
  }
  return title;
});
</script>

<template>
  <AegisActions
    v-if="osimRuntime.flags?.aiTitleSuggestions === true || isTitleAIBot"
    :canSuggest="canSuggest"
    :hasAppliedSuggestion="hasAppliedTitleSuggestion"
    :hasMultipleSuggestions="false"
    :isFetchingSuggestion="isSuggesting"
    :canShowFeedback="canShowTitleFeedbackExtended"
    :isFieldAIBot="isTitleAIBot"
    :suggestions="[]"
    :selectedIndex="0"
    :tooltipText="suggestionTooltip"
    @suggest="suggestDescription"
    @revert="revertTitle"
    @feedback="handleTitleFeedback"
  />
</template>
