<script setup lang="ts">
import { computed, ref, type Ref } from 'vue';

import AegisActions from '@/components/Aegis/AegisActions.vue';

import { useAegisSuggestion } from '@/composables/aegis/useAegisSuggestion';
import type { AegisSuggestionContextRefs } from '@/composables/aegis/useAegisSuggestionContext';
import { useAegisMetadataTracking } from '@/composables/aegis/useAegisMetadataTracking';
import { useSimpleFeedback } from '@/composables/aegis/useUnifiedAegisFeedback';

import { osimRuntime } from '@/stores/osimRuntime';

const props = withDefaults(defineProps<{
  aegisContext?: AegisSuggestionContextRefs | null;
}>(), {
  aegisContext: null,
});

const modelValue = defineModel<null | string[] | undefined>('modelValue');

const {
  allSuggestions,
  canShowFeedback,
  canSuggest,
  details: componentsSuggestionDetails,
  hasAppliedSuggestion,
  isFetchingSuggestion,
  revert: revertComponents,
  selectedSuggestionIndex,
  selectSuggestion,
  sendFeedback,
  suggestComponents,
} = useAegisSuggestion(
  props.aegisContext as AegisSuggestionContextRefs,
  modelValue as Ref<null | string[] | undefined>,
  'components',
);

const { getAIBotEntry, getAIBotTooltip, isFieldValueAIBot } = useAegisMetadataTracking();
const { sendFeedback: sendBotFeedback } = useSimpleFeedback();

const isComponentsAIBot = computed(() => isFieldValueAIBot('components', modelValue.value));
const botFeedbackSent = ref(false);

// Combined feedback logic for both user suggestions and bot suggestions
const canShowFeedbackCombined = computed(() => {
  // Prioritize user suggestion feedback when there's a manual suggestion applied
  if (hasAppliedSuggestion.value) {
    return canShowFeedback.value;
  }

  // Otherwise, show bot feedback if applicable
  if (isComponentsAIBot.value && modelValue.value && !botFeedbackSent.value) {
    return true;
  }

  return false;
});

const handleFeedback = async (kind: 'negative' | 'positive', comment = '') => {
  // Prioritize user suggestion feedback when there's a manual suggestion applied
  if (hasAppliedSuggestion.value) {
    // Handle user suggestion feedback
    return sendFeedback(kind, comment);
  } else if (isComponentsAIBot.value) {
    // Handle AI-Bot feedback - use same feature name and data format as user suggestions
    // Ensure components are always sent as array for consistency
    const actualValue = Array.isArray(modelValue.value) ? modelValue.value : [modelValue.value].filter(Boolean);
    const result = await sendBotFeedback('components', actualValue, kind, comment, 'suggest-affected-components');
    if (result) botFeedbackSent.value = true;
    return result;
  }
};

defineExpose({
  isFetchingSuggestion,
});

const suggestionTooltip = computed(() => {
  let tooltip = '';
  if (hasAppliedSuggestion.value && componentsSuggestionDetails.value?.explanation) {
    const title = isComponentsAIBot.value ? 'Generated by Aegis-AI-Bot' : 'Generated by Aegis-AI';
    tooltip = `${title}\n\n${componentsSuggestionDetails.value.explanation}`;
  } else {
    const aiBotTooltip = getAIBotTooltip('components');
    if (aiBotTooltip !== 'Generated by Aegis-AI-Bot') {
      tooltip = aiBotTooltip.replace(/<br><br>/g, '\n\n');
    }
  }

  const ecosystems = hasAppliedSuggestion.value
    ? componentsSuggestionDetails.value?.ecosystems
    : getAIBotEntry('_ecosystems')?.value;
  if (Array.isArray(ecosystems) && ecosystems.length) {
    const line = `Ecosystems: ${ecosystems.join(', ')}`;
    tooltip = tooltip ? `${tooltip}\n\n${line}` : `Generated by Aegis-AI-Bot\n\n${line}`;
  }

  return tooltip;
});
</script>

<template>
  <AegisActions
    :canSuggest="canSuggest && !!osimRuntime.flags?.aiComponentSuggestions"
    :hasAppliedSuggestion="hasAppliedSuggestion"
    :hasMultipleSuggestions="false"
    :isFetchingSuggestion="isFetchingSuggestion"
    :canShowFeedback="canShowFeedbackCombined"
    :isFieldAIBot="isComponentsAIBot"
    :suggestions="allSuggestions as string[]"
    :selectedIndex="selectedSuggestionIndex"
    :tooltipText="suggestionTooltip"
    @suggest="suggestComponents"
    @selectSuggestion="selectSuggestion"
    @revert="revertComponents"
    @feedback="handleFeedback"
  >
    <template #suggestion-item="{ suggestions, selectedIndex, selectSuggestion: selectSuggestionFn }">
      <li v-for="(suggestionItem, index) in suggestions" :key="index">
        <button
          class="dropdown-item"
          :class="{ 'active': index === selectedIndex }"
          type="button"
          @click="selectSuggestionFn(index)"
        >
          <div class="flex-grow-1 d-flex flex-column" style="gap: 0.15rem;">
            <span class="fw-bold fs-7">{{ suggestionItem }}</span>
          </div>
        </button>
      </li>
    </template>
  </AegisActions>
</template>

<style scoped lang="scss">
.icon-link {
  color: gray;
  text-decoration: none;

  &:hover {
    color: #0d6efd;
  }
}
</style>
