<script setup lang="ts">
import { type Ref, computed } from 'vue';

import AegisActions from '@/components/Aegis/AegisActions.vue';

import { useAegisSuggestion } from '@/composables/aegis/useAegisSuggestion';
import type { AegisSuggestionContextRefs } from '@/composables/aegis/useAegisSuggestionContext';
import { useAegisFieldFeedback } from '@/composables/aegis/useAegisFieldFeedback';
import { useAegisMetadataTracking } from '@/composables/aegis/useAegisMetadataTracking';

import { osimRuntime } from '@/stores/osimRuntime';

const props = withDefaults(defineProps<{
  aegisContext?: AegisSuggestionContextRefs | null;
}>(), {
  aegisContext: null,
});

const modelValue = defineModel<null | string>('modelValue');

const {
  allSuggestions,
  canShowFeedback,
  canSuggest,
  currentSuggestion: _currentStatement,
  details: statementSuggestionDetails,
  hasAppliedSuggestion,
  hasMultipleSuggestions,
  isFetchingSuggestion,
  revert: revertStatement,
  selectedSuggestionIndex,
  selectSuggestion,
  sendFeedback,
  suggestStatement,
} = useAegisSuggestion(
  props.aegisContext as AegisSuggestionContextRefs,
  modelValue as Ref<null | string>,
  'statement',
);

const { getAIBotTooltip } = useAegisMetadataTracking();

const {
  canShowFeedbackExtended,
  handleFieldFeedback: handleStatementFeedback,
  isFieldAIBot: isStatementAIBot,
} = useAegisFieldFeedback(
  'statement',
  modelValue,
  canShowFeedback,
  hasAppliedSuggestion,
  sendFeedback,
);

defineExpose({
  isFetchingSuggestion,
});

const suggestionTooltip = computed(() => {
  // If field is AI-Bot from history, use the tooltip from metadata
  if (isStatementAIBot.value && !hasAppliedSuggestion.value) {
    const tooltip = getAIBotTooltip('statement');
    // Convert <br> to \n for consistency with other tooltips
    return tooltip.replace(/<br><br>/g, '\n\n');
  }

  // Otherwise use the suggestion details if available
  if (!hasAppliedSuggestion.value || !statementSuggestionDetails.value) return 'Generated by Aegis-AI';
  const { explanation } = statementSuggestionDetails.value;
  const title = isStatementAIBot.value ? 'Generated by Aegis-AI-Bot' : 'Generated by Aegis-AI';
  if (explanation) {
    return `${title}\n\n${explanation}`;
  }
  return title;
});
</script>

<template>
  <AegisActions
    v-if="osimRuntime.flags?.aiStatementSuggestions || isStatementAIBot"
    :canSuggest="canSuggest"
    :hasAppliedSuggestion="hasAppliedSuggestion"
    :hasMultipleSuggestions="hasMultipleSuggestions"
    :isFetchingSuggestion="isFetchingSuggestion"
    :canShowFeedback="canShowFeedbackExtended"
    :isFieldAIBot="isStatementAIBot"
    :suggestions="allSuggestions as string[]"
    :selectedIndex="selectedSuggestionIndex"
    :tooltipText="suggestionTooltip"
    @suggest="suggestStatement"
    @selectSuggestion="selectSuggestion"
    @revert="revertStatement"
    @feedback="handleStatementFeedback"
  />
</template>

<style scoped lang="scss">
.icon-link {
  color: gray;
  text-decoration: none;

  &:hover {
    color: #0d6efd;
  }
}
</style>
