<script setup lang="ts">
import { computed, ref, onMounted } from 'vue';

import AegisActions from '@/components/Aegis/AegisActions.vue';

import { useAegisSuggestion } from '@/composables/aegis/useAegisSuggestion';
import type { AegisSuggestionContextRefs } from '@/composables/aegis/useAegisSuggestionContext';
import { useAegisFieldFeedback } from '@/composables/aegis/useAegisFieldFeedback';
import { useAegisMetadataTracking } from '@/composables/aegis/useAegisMetadataTracking';

import { osimRuntime } from '@/stores/osimRuntime';
import { getMitreUrl, loadCweData } from '@/services/CweService';
import type { CWEMemberType } from '@/types/mitreCwe';

const props = withDefaults(defineProps<{
  aegisContext?: AegisSuggestionContextRefs | null;
  cweData?: CWEMemberType[];
}>(), {
  aegisContext: null,
  cweData: () => [],
});

const modelValue = defineModel<null | string>('modelValue', { default: null });

const cweDataRef = ref<CWEMemberType[]>([]);

const {
  allSuggestions,
  canShowFeedback,
  canSuggest,
  currentSuggestion: _currentCwe,
  details: suggestionDetails,
  hasAppliedSuggestion,
  hasMultipleSuggestions,
  isFetchingSuggestion,
  revert: revertCwe,
  selectedSuggestionIndex,
  selectSuggestion,
  sendFeedback,
  suggestCwe,
} = useAegisSuggestion(props.aegisContext as AegisSuggestionContextRefs, modelValue, 'cwe_id');

const { getAIBotTooltip } = useAegisMetadataTracking();

const {
  canShowFeedbackExtended,
  handleFieldFeedback: handleCweFeedback,
  isFieldAIBot: isCweAIBot,
} = useAegisFieldFeedback(
  'cwe_id',
  modelValue,
  canShowFeedback,
  hasAppliedSuggestion,
  sendFeedback,
);

defineExpose({
  isFetchingSuggestion,
});

const suggestionTooltip = computed(() => {
  // If field is AI-Bot from history, use the tooltip from metadata
  if (isCweAIBot.value && !hasAppliedSuggestion.value) {
    const tooltip = getAIBotTooltip('cwe_id');
    // Convert <br> to \n for consistency with other tooltips
    return tooltip.replace(/<br><br>/g, '\n\n');
  }

  // Otherwise use the suggestion details if available
  if (!hasAppliedSuggestion.value || !suggestionDetails.value) return 'Generated by Aegis-AI';
  const { explanation } = suggestionDetails.value;
  const title = isCweAIBot.value ? 'Generated by Aegis-AI-Bot' : 'Generated by Aegis-AI';
  if (explanation) {
    return `${title}\n\n${explanation}`;
  }
  return title;
});

function getCweDetails(cweId: string): CWEMemberType | null {
  const id = cweId.replace('CWE-', '');
  return cweDataRef.value.find(cwe => cwe.id === id) || null;
}

onMounted(() => {
  // Use provided cweData prop if available, otherwise load from localStorage
  cweDataRef.value = props.cweData.length > 0
    ? props.cweData
    : loadCweData().filter(({ isProhibited }) => !isProhibited);
});
</script>

<template>
  <AegisActions
    v-if="osimRuntime.flags?.aiCweSuggestions === true || isCweAIBot"
    :canSuggest="canSuggest"
    :hasAppliedSuggestion="hasAppliedSuggestion"
    :hasMultipleSuggestions="hasMultipleSuggestions"
    :isFetchingSuggestion="isFetchingSuggestion"
    :canShowFeedback="canShowFeedbackExtended"
    :isFieldAIBot="isCweAIBot"
    :suggestions="allSuggestions as string[]"
    :selectedIndex="selectedSuggestionIndex"
    :tooltipText="suggestionTooltip"
    @suggest="suggestCwe"
    @selectSuggestion="selectSuggestion"
    @revert="revertCwe"
    @feedback="handleCweFeedback"
  >
    <template #suggestion-item="{ suggestions, selectedIndex, selectSuggestion: selectSuggestionFn }">
      <li v-for="(suggestion, index) in suggestions" :key="index">
        <button
          class="dropdown-item"
          :class="{ 'active': index === selectedIndex }"
          type="button"
          @click="selectSuggestionFn(index)"
        >
          <div class="flex-grow-1 d-flex flex-column" style="gap: 0.15rem;">
            <span class="fw-bold fs-7">{{ suggestion }}</span>
            <small v-if="getCweDetails(suggestion)" class="text-muted small">
              {{ getCweDetails(suggestion)!.name }}
            </small>
          </div>
          <a
            v-if="getCweDetails(suggestion)"
            :href="getMitreUrl(getCweDetails(suggestion)!.id)"
            class="icon-link"
            target="_blank"
            @click.stop
          >
            <i class="bi-box-arrow-up-right" title="View on Mitre" />
          </a>
        </button>
      </li>
    </template>
  </AegisActions>
</template>

<style scoped lang="scss">
.icon-link {
  color: gray;
  text-decoration: none;

  &:hover {
    color: #0d6efd;
  }
}
</style>
