<script setup lang="ts">
import { type Ref, computed, watch } from 'vue';

import AegisActions from '@/components/Aegis/AegisActions.vue';

import { useAegisSuggestion } from '@/composables/aegis/useAegisSuggestion';
import type { AegisSuggestionContextRefs } from '@/composables/aegis/useAegisSuggestionContext';
import { useAegisFieldFeedback } from '@/composables/aegis/useAegisFieldFeedback';
import { useAegisMetadataTracking } from '@/composables/aegis/useAegisMetadataTracking';

import type { ImpactEnumWithBlankType } from '@/types/zodShared';

const props = withDefaults(defineProps<{
  aegisContext?: AegisSuggestionContextRefs | null;
}>(), {
  aegisContext: null,
});

const modelValue = defineModel<null | string>('modelValue');

const emit = defineEmits<{
  (e: 'update:impact', value: null | string | undefined): void;
}>();

watch(modelValue, (newValue) => {
  emit('update:impact', newValue);
});

const {
  allSuggestions,
  canShowFeedback,
  canSuggest,
  currentSuggestion: _currentImpact,
  details: impactSuggestionDetails,
  hasAppliedSuggestion,
  hasMultipleSuggestions,
  isFetchingSuggestion,
  revert: revertImpact,
  selectedSuggestionIndex,
  selectSuggestion,
  sendFeedback,
  suggestImpact,
} = useAegisSuggestion(
  props.aegisContext as AegisSuggestionContextRefs,
  modelValue as Ref<ImpactEnumWithBlankType | null | string>,
  'impact',
);

const { getAIBotTooltip } = useAegisMetadataTracking();

const {
  canShowFeedbackExtended,
  handleFieldFeedback: handleImpactFeedback,
  isFieldAIBot: isImpactAIBot,
} = useAegisFieldFeedback(
  'impact',
  modelValue,
  canShowFeedback,
  hasAppliedSuggestion,
  sendFeedback,
);

defineExpose({
  isFetchingSuggestion,
});

const suggestionTooltip = computed(() => {
  // If there's a current applied suggestion with details, use that
  if (hasAppliedSuggestion.value && impactSuggestionDetails.value?.explanation) {
    const title = isImpactAIBot.value ? 'Generated by Aegis-AI-Bot' : 'Generated by Aegis-AI';
    return `${title}\n\n${impactSuggestionDetails.value.explanation}`;
  }

  // Otherwise try to get AI-Bot tooltip content
  const aiBotTooltip = getAIBotTooltip('impact');
  if (aiBotTooltip && aiBotTooltip !== 'Generated by Aegis-AI-Bot') {
    return aiBotTooltip.replace(/<br><br>/g, '\n\n');
  }

  return '';
});
</script>

<template>
  <AegisActions
    :canSuggest="canSuggest"
    :hasAppliedSuggestion="hasAppliedSuggestion"
    :hasMultipleSuggestions="hasMultipleSuggestions"
    :isFetchingSuggestion="isFetchingSuggestion"
    :canShowFeedback="canShowFeedbackExtended"
    :isFieldAIBot="isImpactAIBot"
    :suggestions="allSuggestions as string[]"
    :selectedIndex="selectedSuggestionIndex"
    :tooltipText="suggestionTooltip"
    @suggest="suggestImpact"
    @selectSuggestion="selectSuggestion"
    @revert="revertImpact"
    @feedback="handleImpactFeedback"
  />
</template>

<style scoped lang="scss">
.icon-link {
  color: gray;
  text-decoration: none;

  &:hover {
    color: #0d6efd;
  }
}
</style>
