<script setup lang="ts">
import { computed } from 'vue';

import AegisActions from '@/components/Aegis/AegisActions.vue';

import type { UseAegisSuggestDescriptionReturn } from '@/composables/aegis/useAegisSuggestDescription';
import { useAegisFieldFeedback } from '@/composables/aegis/useAegisFieldFeedback';
import { useAegisMetadataTracking } from '@/composables/aegis/useAegisMetadataTracking';

import { osimRuntime } from '@/stores/osimRuntime';

const props = defineProps<{
  composable: UseAegisSuggestDescriptionReturn;
  descriptionValue?: null | string;
}>();

const {
  canShowDescriptionFeedback,
  canSuggest,
  details: suggestionDetails,
  hasAppliedDescriptionSuggestion,
  isSuggesting,
  revertDescription,
  sendDescriptionFeedback,
  suggestDescription,
} = props.composable;

defineExpose({
  isSuggesting,
});

const { getAIBotTooltip } = useAegisMetadataTracking();

const {
  canShowFeedbackExtended: canShowDescriptionFeedbackExtended,
  handleFieldFeedback: handleDescriptionFeedback,
  isFieldAIBot: isDescriptionAIBot,
} = useAegisFieldFeedback(
  'cve_description',
  computed(() => props.descriptionValue),
  canShowDescriptionFeedback,
  hasAppliedDescriptionSuggestion,
  sendDescriptionFeedback,
);

const suggestionTooltip = computed(() => {
  // If field is AI-Bot from history, use the tooltip from metadata
  if (isDescriptionAIBot.value && !hasAppliedDescriptionSuggestion.value) {
    const tooltip = getAIBotTooltip('cve_description');
    // Convert <br> to \n for consistency with other tooltips
    return tooltip.replace(/<br><br>/g, '\n\n');
  }

  // Otherwise use the suggestion details if available
  if (!hasAppliedDescriptionSuggestion.value || !suggestionDetails.value) {
    return 'Generated by Aegis-AI';
  }
  const { explanation } = suggestionDetails.value;
  const title = isDescriptionAIBot.value ? 'Generated by Aegis-AI-Bot' : 'Generated by Aegis-AI';
  if (explanation) {
    return `${title}\n\n${explanation}`;
  }
  return title;
});
</script>

<template>
  <AegisActions
    v-if="osimRuntime.flags?.aiDescriptionSuggestions === true || isDescriptionAIBot"
    :canSuggest="canSuggest"
    :hasAppliedSuggestion="hasAppliedDescriptionSuggestion"
    :hasMultipleSuggestions="false"
    :isFetchingSuggestion="isSuggesting"
    :canShowFeedback="canShowDescriptionFeedbackExtended"
    :isFieldAIBot="isDescriptionAIBot"
    :suggestions="[]"
    :selectedIndex="0"
    :tooltipText="suggestionTooltip"
    @suggest="suggestDescription"
    @revert="revertDescription"
    @feedback="handleDescriptionFeedback"
  />
</template>
