apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: osim-imagestream
  namespace: osim-ui--runtime-int
spec:
  lookupPolicy:
    local: false
  tags:
  - name: latest
    from:
      kind: DockerImage
      name: quay.io/samwalke/osim:latest
    importPolicy:
      scheduled: true
