import type { SRPReport, SRPReportMilestonePayloadField } from '@/types/cra';

function payloadField(
  key: string,
  label: string,
  value: unknown,
  requirement: SRPReportMilestonePayloadField['requirement'],
  editable = true,
  input_type = 'text',
  options: string[] = [],
): SRPReportMilestonePayloadField {
  return {
    editable,
    input_type,
    key,
    label,
    missing: requirement === 'required' && (value === '' || (Array.isArray(value) && value.length === 0)),
    options,
    requirement,
    section: 'common',
    source: 'generated',
    value,
  };
}

export const mockAEVPayloadFields: SRPReportMilestonePayloadField[] = [
  payloadField('notification_type', 'Notification Type', 'Vulnerability', 'required', false),
  payloadField('report_title', 'Title', 'Test SRP Report', 'required'),
  payloadField('summary', 'Summary', 'Sample summary', 'required', true, 'textarea'),
  payloadField('manufacturer_or_steward_name', 'Manufacturer Name', 'Red Hat', 'required'),
  payloadField(
    'member_states_available',
    'Member States Where Product Available (Concerned CSIRT)',
    ['DE'],
    'required',
    true,
    'multi_select',
    ['AT', 'DE', 'EL'],
  ),
  payloadField('product_name', 'Product Name', 'Red Hat Enterprise Linux', 'required'),
  payloadField('product_version', 'Product Version', '9', 'required'),
  payloadField('product_type', 'Product Type', '', 'optional'),
  payloadField('product_class', 'Product Class', '', 'optional'),
  payloadField('product_category', 'Product Category', '', 'optional'),
  payloadField('end_of_support', 'End of Support Indicator', '', 'optional', true, 'boolean'),
  payloadField('component_name', 'Component Name', 'kernel', 'optional'),
  payloadField(
    'mitigating_measure_expected_shortly',
    'Mitigating Measure Expected Shortly',
    '',
    'optional',
    true,
    'boolean',
  ),
  payloadField('cve_id', 'CVE ID', 'CVE-2026-1234', 'optional'),
  payloadField('euvd_id', 'EUVD ID', '', 'optional', true, 'text'),
  payloadField('general_information', 'General Information', '', 'optional', true, 'textarea'),
  payloadField(
    'aev_detected_at',
    'Date and Time When You Become Aware of the Actively Exploited Vulnerability',
    '2026-01-01T00:00:00Z',
    'required',
    true,
    'datetime',
  ),
  payloadField(
    'corrective_or_mitigating_measures_taken',
    'Corrective or Mitigating Measures Taken',
    '',
    'optional',
    true,
    'textarea',
  ),
  payloadField(
    'corrective_or_mitigating_measures_users_can_take',
    'Corrective or Mitigating Measures That Users Can Take',
    '',
    'optional',
    true,
    'textarea',
  ),
];

export const mockSIPayloadFields: SRPReportMilestonePayloadField[] = [
  payloadField('notification_type', 'Notification Type', 'Incident', 'required', false),
  payloadField('report_title', 'Title', 'Test SI Report', 'required'),
  payloadField('summary', 'Summary', 'Sample incident summary', 'required', true, 'textarea'),
  payloadField('manufacturer_or_steward_name', 'Manufacturer Name', 'Red Hat', 'required'),
  payloadField(
    'member_states_available',
    'Member States Where Product Available (Concerned CSIRT)',
    ['DE'],
    'required',
    true,
    'multi_select',
    ['AT', 'DE', 'EL'],
  ),
  payloadField('product_name', 'Product Name', 'Red Hat Enterprise Linux', 'required'),
  payloadField('product_version', 'Product Version', '9', 'required'),
  payloadField('product_type', 'Product Type', '', 'optional'),
  payloadField('product_class', 'Product Class', '', 'optional'),
  payloadField('product_category', 'Product Category', '', 'optional'),
  payloadField('end_of_support', 'End of Support Indicator', '', 'optional', true, 'boolean'),
  payloadField('component_name', 'Component Name', 'kernel', 'optional'),
  payloadField(
    'mitigating_measure_expected_shortly',
    'Mitigating Measure Expected Shortly',
    '',
    'optional',
    true,
    'boolean',
  ),
  payloadField(
    'suspected_unlawful_or_malicious_acts',
    'Incident Is Suspected of Unlawful or Malicious Acts',
    '',
    'required',
    true,
    'boolean',
  ),
  payloadField(
    'general_incident_information',
    'General Information About the Nature of the Incident',
    '',
    'optional',
    true,
    'textarea',
  ),
  payloadField(
    'incident_detected_at',
    'Date and Time When You Become Aware of the Incident (UTC time)',
    '2026-01-01T00:00:00Z',
    'required',
    true,
    'datetime',
  ),
  payloadField(
    'incident_occurred_at',
    'Date and Time When the Incident Occurred (UTC time)',
    '',
    'optional',
    true,
    'datetime',
  ),
  payloadField(
    'initial_incident_assessment',
    'Initial Assessment of the Incident',
    '',
    'optional',
    true,
    'textarea',
  ),
];

export const mockSRPReport: SRPReport = {
  created_dt: '2026-01-01T00:00:00Z',
  designated_csirt_country: '',
  designated_csirt_source: '',
  evidence: 'Sample evidence for test report',
  flaw_id: 'FLAW-123',
  manufacturer_or_steward_name: '',
  member_states_available: [],
  milestones: [{
    acl_read: [],
    acl_write: [],
    created_dt: '2026-01-01T00:00:00Z',
    days_remaining: 5,
    due_at: '2026-01-20T12:30:00Z',
    hours_remaining: 125,
    is_overdue: false,
    manual_completion_notes: '',
    milestone_type: '24h',
    missing_required_fields: '',
    payload_fields: mockAEVPayloadFields,
    request_received_at: null,
    request_source: '',
    request_text: '',
    srp_report: 'report-123',
    status: 'in_progress',
    updated_dt: '2026-01-05T00:00:00Z',
    uuid: 'milestone-1',
  }],
  missing_required_fields: '',
  reportable_event_type: 'EXPLOITS_KEV_APPROVED',
  responsibility_scope: 'manufacturer',
  srp_reference_id: 'SRP-123',
  srp_reference_url: 'https://example.com/srp-123',
  status: 'in_progress',
  timer_started_at: null,
  title: 'Test SRP Report',
  updated_dt: '2026-01-05T00:00:00Z',
  uuid: 'report-123',
};
