import type { SRPReport } from '@/types/cra';

export const mockSRPReport: SRPReport = {
  created_dt: '2026-01-01T00:00:00Z',
  designated_csirt_country: '',
  designated_csirt_source: '',
  flaw_id: 'FLAW-123',
  manufacturer_or_steward_name: '',
  member_states_available: [],
  milestones: [{
    acl_read: [],
    acl_write: [],
    created_dt: '2026-01-01T00:00:00Z',
    days_remaining: 5,
    due_at: '2026-01-20T12:30:00Z',
    hours_remaining: 125,
    is_overdue: false,
    manual_completion_notes: '',
    milestone_type: '24h',
    missing_required_fields: '',
    request_received_at: null,
    request_source: '',
    request_text: '',
    srp_report: 'report-123',
    status: 'prepared',
    updated_dt: '2026-01-05T00:00:00Z',
    uuid: 'milestone-1',
  }],
  reportable_event_type: 'actively_exploited_vulnerability',
  responsibility_scope: 'manufacturer',
  srp_reference_id: 'SRP-123',
  srp_reference_url: 'https://example.com/srp-123',
  status: 'required',
  timer_started_at: null,
  title: 'Test SRP Report',
  updated_dt: '2026-01-05T00:00:00Z',
  uuid: 'report-123',
};
