name: Deploy Images to GHCR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  push-store-image:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './store'
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    - name: 'Build and Push Image'
      run: |
        # Use the branch name as the image tag for PR events, and use "latest" for push events to main
        if [[ ${{ github.event_name }} == "pull_request" ]]; then
          IMAGE_TAG="${{ github.event.pull_request.head.ref }}"
        else
          IMAGE_TAG="latest"
        fi
        IMAGE_NAME="ghcr.io/RedHatProductSecurity/ir-web-ui:${IMAGE_TAG}"
        docker build . -t ${IMAGE_NAME}
        docker push ${IMAGE_NAME}
